module.exports = [
  {id:56,theme:'Bốn Sách Tin Mừng',words:[
    {answer:'MATTHEU',clue:'Tác giả sách thứ nhất vốn là một viên chức thu thuế đã đứng lên từ bỏ mọi sự để đi theo tiếng gọi của Chúa.',explanation:'Sách Mát-thêu đặc biệt hướng đến độc giả gốc Do Thái, trưng dẫn các lời sấm Cựu Ước để chứng minh Đức Giêsu là Đấng Mêsia thuộc dòng dõi Đavít.'},
    {answer:'MACCO',clue:'Cuốn Phúc Âm lâu đời và ngắn gọn nhất, mang nhịp điệu dồn dập miêu tả sống động các hoạt động uy quyền của Chúa.',explanation:'Thánh Máccô ghi chép lại lời giảng của thánh Phêrô, nổi bật với cụm từ "lập tức" lặp đi lặp lại để mô tả uy quyền của Chúa Giêsu.'},
    {answer:'LUCA',clue:'Vị y sĩ uyên bác phác họa nên bức chân dung dung dị và sâu sắc về sự nhân hậu bao dung của Chúa Giêsu.',explanation:'Luca được mệnh danh là người viết Tin Mừng của lòng thương xót, với những dụ ngôn kinh điển bất hủ như Người Cha Nhân Hậu và Người Samari Tốt Lành.'},
    {answer:'GIOAN',clue:'Người môn đệ Chúa yêu chắp bút cuốn Phúc Âm thứ tư mang chiều sâu thần học chiêm niệm siêu việt.',explanation:'Sách Gioan mang biểu tượng đại bàng bay vút cao, không chú trọng thuật lại bối cảnh lịch sử mà xoáy sâu vào các bài giảng và diễn từ vĩ đại "Ta là".'},
    {answer:'NHAPTHE',clue:'Mầu nhiệm cao cả khi Ngôi Lời vô biên quyền phép rũ bỏ vinh quang để xuống thế mang lấy xác phàm.',explanation:'Tin Mừng thứ tư mở ra một thực tại chói lòa: Ngôi Lời đã trở nên người phàm và cư ngụ giữa chúng ta, nối kết đất với trời.'},
    {answer:'TINMUNG',clue:'Bốn cuốn sách đầu của bộ Tân Ước, tường thuật chân thực cuộc đời, lời giảng dạy và sự sống lại của Chúa Giêsu.',explanation:'Phúc Âm (Tin Mừng) không chỉ là văn bản lịch sử mà là quyền năng cứu độ của Thiên Chúa dành cho tất cả những ai sẵn sàng mở lòng đón nhận.'},
  ]},
  {id:57,theme:'Tuần Thánh Khổ Nạn',words:[
    {answer:'LELA',clue:'Cột mốc khai màn Tuần Thánh khi dân chúng cầm nhành cây vẫy chào trải áo và tung hô Vua khải hoàn vào thành.',explanation:'Sự kiện phô diễn tung hô mang dư vị xót xa, vì chính đám đông vang tiếng "Hoan hô" này chẳng mấy chốc sẽ la thét đòi đóng đinh Người.'},
    {answer:'THUNAM',clue:'Đêm cực thánh khai mạc Tam Nhật Vượt Qua, chứa đựng Bữa Tiệc Ly lịch sử nơi Chúa cúi mình rửa chân cho môn đệ.',explanation:'Thứ Năm Tuần Thánh thiết lập Bí Tích Thánh Thể và chức Tư tế, đồng thời khởi đầu bi kịch Giuđa nộp Thầy bằng một nụ hôn phản bội.'},
    {answer:'THUSAU',clue:'Ngày bi thương khi bầu trời sập tối lúc ba giờ chiều, thời khắc Đấng Cứu Thế trút hơi thở cuối cùng trên thập tự.',explanation:'Toàn thể Giáo Hội phủ phục suy tôn Thánh Giá ô nhục, nay đã hóa thân rực rỡ thành biểu tượng chiến thắng vượt qua tội lỗi và cái chết.'},
    {answer:'MOTRONG',clue:'Bằng chứng thinh lặng nhưng hùng hồn vào sáng sớm ngày Chúa Nhật, khi tảng đá lấp cửa mồ đã bị lăn sang một bên.',explanation:'Ngôi mộ vắng tanh với khăn liệm và dây băng xếp gọn gàng xóa nhòa mọi phỏng đoán mơ hồ, để lộ manh mối minh chứng quyền năng Phục Sinh.'},
    {answer:'PHUCSINH',clue:'Biến cố vĩ đại lật ngược thế cờ đập tan sự kiềm tỏa của thần chết, đem lại ánh bình minh khải hoàn của sự sống bất tử.',explanation:'Chúa Kitô Phục Sinh mang theo các thương tích cuộc Khổ Nạn, nay đã sáng láng thành dấu ấn hiển vinh vượt thắng đem ơn cứu rỗi cho nhân loại.'},
    {answer:'GIETSIMANI',clue:'Khu vườn nơi Chúa sấp mặt nài xin Cha cất chén đắng, toát mồ hôi hòa lẫn những giọt máu tuôn rơi rơi xuống đất.',explanation:'Gethsemane là giờ phút gánh vác cô đơn tột bậc của Chúa. Ngài ôm trọn mọi tội lỗi của nhân thế để vững vàng tuân phục vâng theo Thánh Ý Cha.'},
  ]},
  {id:58,theme:'Giai Đoạn Sáng Thế',words:[
    {answer:'BABEN',clue:'Ngôi tháp kiêu ngạo bị Thiên Chúa can thiệp xây dở dang nhằm chia rẽ ngôn ngữ loài người, khi họ muốn đồng mưu vươn tới trời cao.',explanation:'Biến cố ngọn tháp Babel là hậu quả của tội tự suy tôn mình, làm tan vỡ âm mưu kiêu ngạo muốn làm trái trật tự của Đấng Tạo Hóa.'},
    {answer:'LAMEC',clue:'Hậu duệ hung tợn của Cain lên tiếng khoác lác một bài ca bạo lực khát máu, thề trả thù bạo hành gấp bảy mươi bảy lần.',explanation:'Bài ca của Lamec chứng minh sự lan tràn hung bạo của tội ác nơi loài người thời nguyên thủy tiếp nối sau khi tổ tông sa ngã.'},
    {answer:'HENOC',clue:'Bậc tổ phụ sống công chính và gắn bó mật thiết với Thiên Chúa đến mức được rước thẳng lên trời mà không qua cái chết.',explanation:'Sách Sáng Thế phác họa Hênóc luôn đi dạo đồng hành với Chúa. Cuộc đời của ngài là hình bóng của những tâm hồn công chính được đưa về nhan thánh.'},
    {answer:'MATHUXALA',clue:'Vị tổ phụ sống thọ nhất Kinh Thánh với tuổi đời ghi nhận là chín trăm sáu mươi chín năm ở thời kỳ trước Hồng Thủy.',explanation:'Tuổi thọ vĩ đại thời Cựu Ước bày tỏ sự trường tồn và phúc lành Chúa ban cho con người, trước khi tội lỗi dần phá mòn đi tất cả.'},
    {answer:'SODOM',clue:'Tòa thành chìm ngập trong tội lỗi tột độ đã bị phán xét tiêu hủy bằng những trận mưa sinh diêm cháy lửa từ trời.',explanation:'Dù tổ phụ Ápraham đã thành tâm khẩn nài thỉnh nguyện nhưng không thể vớt vát tìm ra nổi mười người công chính tại Sôđôm nên tòa thành vẫn bị hình phạt.'},
    {answer:'MENKIXEDE',clue:'Vị vua kiêm tư tế bí ẩn thành Salem mang bánh miến và rượu nho dâng lên để chúc lành cho tổ phụ Ápraham.',explanation:'Tư tế tối cao Menkixêđê là một hình bóng nhiệm mầu không ghi chép gia phả, tiên báo chức tư tế muôn đời thượng phẩm của Đức Kitô.'},
  ]},
  {id:59,theme:'Các Thư Thánh Phaolô',words:[
    {answer:'ROMA',clue:'Bức thư đồ sộ và nền tảng trình bày giáo thuyết thần học về ơn cứu độ ngang qua đức tin xưng công chính hóa.',explanation:'Tâm điểm thư Rôma khẳng định ơn cứu độ là hồng ân nhưng không Thiên Chúa ban tặng, thay vì trông cậy vào công lao tự sức thực hành lề luật.'},
    {answer:'CORINTO',clue:'Cộng đoàn Hy Lạp phức tạp được vị tông đồ viết thư nhắc nhở chấn chỉnh sự chia rẽ và gửi gắm bài ca Đức Ái nổi tiếng.',explanation:'Các thư gửi tín hữu Côrintô vừa củng cố trật tự cử hành Thánh Thể, vừa tuôn trào tâm tình biện hộ cho sứ vụ tông đồ đầy rẫy chông gai gian truân.'},
    {answer:'GALATA',clue:'Bức thư mang tính thức tỉnh mạnh mẽ nhằm phản bác nhóm người muốn ép buộc người tân tòng gốc dân ngoại phải chịu phép cắt bì.',explanation:'Thư Galata khẳng định giải phóng con cái Đức Chúa khỏi hệ thống lề luật cũ, tuyên xưng tự do trọn vẹn đạt được nhờ Thập Giá Chúa Kitô.'},
    {answer:'EPHEXO',clue:'Bức thư viết từ ngục thất Rôma trình bày mầu nhiệm Giáo Hội mang hình ảnh Nhiệm Thể mà Chúa Kitô là thủ lãnh tối cao.',explanation:'Cộng đoàn Êphêxô nhận được huấn dụ hãy mặc lấy mọi vũ khí thiêng liêng vững bền của Thiên Chúa để đứng vững trước những mưu chước ma quỷ.'},
    {answer:'PHILIPHE',clue:'Lá thư được dệt nên bằng tâm tình chan chứa niềm vui và lòng bác ái trào dâng, dù được viết ngay giữa hoàn cảnh chịu gông cùm.',explanation:'Dù đang chịu cảnh lao tù, vị thánh tông đồ vẫn tung hô khích lệ cộng đoàn Philíp luôn giữ niềm vui bình an, hướng về sự tự hạ của Chúa Kitô.'},
    {answer:'HEBORO',clue:'Bức thư xoáy sâu chứng minh quyền năng Chúa Giêsu là Vị Thượng Tế độc nhất dâng mình làm của lễ vĩnh viễn thay thế mọi tế tự cũ.',explanation:'Thư Hêbơrơ khẳng định hy lễ thập giá của Chúa Kitô là hiến lễ dứt khoát cứu chuộc trọn đời một lần đã thành toàn mọi nghi thể Cựu Ước.'},
  ]},
  {id:60,theme:'Hội Thánh Sơ Khai',words:[
    {answer:'HIENXUONG',clue:'Sự kiện cơn gió mạnh lùa vào nhà và những hình lưỡi lửa đáp xuống ban Chúa Thánh Thần cho các tông đồ.',explanation:'Lễ Hiện Xuống đánh dấu ngày khai sinh của Giáo Hội, xóa bỏ mọi sợ hãi e dè để các Tông đồ mạnh dạn ra đi loan báo Tin Mừng.'},
    {answer:'PHERO',clue:'Vị tông đồ trưởng đã mạnh dạn đứng lên giảng thuyết thu phục ba ngàn người chịu phép Rửa Tội trong ngày đầu tiên của Giáo Hội.',explanation:'Từ một người từng chối Chúa, Thánh Phêrô lãnh nhận ơn Thánh Thần để can đảm dẫn dắt đoàn chiên bất chấp mọi lời đe dọa tù đày.'},
    {answer:'TEPHANO',clue:'Vị tử đạo tiên khởi đã hân hoan ngước lên thấy vinh quang Thiên Chúa khi hứng chịu cơn mưa đá vùi dập thân mình tử đạo.',explanation:'Dù gánh chịu cái chết bất công bạo hành, phó tế Têphanô vẫn noi gương tha thứ của Chúa Giêsu khi cầu xin án ân cho kẻ bách hại mình.'},
    {answer:'ANTIOKHIA',clue:'Nơi hội tụ các tín hữu gốc dân ngoại, cũng là nơi đầu tiên mà những môn đệ theo đạo được gọi là "Kitô hữu".',explanation:'Thành phố Antiôkhia vinh dự trở thành bàn đạp xuất phát điểm quan trọng cho các hành trình truyền giáo tiến bước vào thế giới dân ngoại.'},
    {answer:'CONGVU',clue:'Cuốn Kinh Thánh tường thuật lại những bước đi mở rộng biên giới truyền giáo của các môn đệ tiên khởi.',explanation:'Tác phẩm thứ hai của thánh Luca vẽ ra bức tranh phát triển của Hội Thánh, khởi hành từ Giêrusalem rồi lan tỏa mạnh mẽ đến thủ phủ Rôma.'},
    {answer:'PHAOLO',clue:'Vị bách hại khét tiếng bị ngã ngựa mù lòa sau đó biến đổi trở thành Tông đồ vĩ đại chuyên mở đường rao giảng nơi dân ngoại.',explanation:'Saolô trở lại và đổi tên thành Phaolô, trải qua muôn vàn lao tù thập tử nhất sinh để gieo hạt mầm Đức Tin gặt hái cánh đồng dân ngoại.'},
  ]},
  { id: 121, theme: 'XH 20: Mười Điều Răn (2)', words: [
    { answer: 'CHA', clue: 'Bậc sinh thành mà lề luật buộc con cái phải kính trọng vâng lời và phụng dưỡng suốt đời trọn vẹn hiếu đạo.', explanation: 'Điều răn thứ tư là điều răn duy nhất có đính kèm lời hứa ban phúc: "Để tuổi thọ ngươi được kéo dài trên đất Chúa ban".' },
    { answer: 'ME', clue: 'Người phụ nữ cưu mang chín tháng mười ngày, có bình đẳng phẩm giá với người cha trong điều răn hiếu thảo.', explanation: 'Tôn trọng bậc sinh thành là tôn vinh chính Thiên Chúa, Đấng đã mượn bàn tay và hơi ấm cha mẹ để thông ban hồng ân sự sống.' },
    { answer: 'GIET', clue: 'Hành động đoạt mạng sống tha nhân một cách bất công tàn bạo, vi phạm cố sát nghiêm trọng giới răn thứ năm.', explanation: 'Chỉ riêng Thiên Chúa là chủ thể tuyệt đối của sự sống tử sinh. Cướp đi sinh mệnh tha nhân là tước đoạt quyền siêu việt của Ngài.' },
    { answer: 'NGOAITINH', clue: 'Sự phản bội lời thề chung thủy hôn nhân, vi phạm giới răn thứ sáu vốn nhằm bảo vệ bản chất thánh thiện gia đình.', explanation: 'Cấm dự phần ngoại tình là rào cản nền tảng bảo vệ sự hiệp nhất thiêng liêng gia đình khỏi đớn đau của sự ích kỷ và nhục dục phá vỡ.' },
    { answer: 'TROMCAP', clue: 'Hành vi lén lút hay công khai chiếm đoạt tài sản vốn của người khác, một giới cấm được đặt ra tại điều răn thứ bảy.', explanation: 'Cấm trộm cắp là nền tảng của công bằng bác ái xã hội, bảo vệ quyền tư hữu hợp lệ và chống lại lề thói tham lam xảo quyệt.' },
    { answer: 'CHUNGDOC', clue: 'Hành vi thề gian làm hại người thân cận vô tội trước tòa án hay trong cộng đồng, vi phạm trực tiếp ác ngôn điều răn thứ tám.', explanation: 'Lời chứng dối làm rạn nứt lòng tin chung tín. Thiên Chúa là Đấng chân thật, do đó yêu mến Ngài đòi buộc đời sống minh bạch thẳng ngay.' }
  ]},
  { id: 122, theme: 'XH 21: Luật Về Quyền Lợi', words: [
    { answer: 'NOLE', clue: 'Tầng lớp lao dịch mà luật quy định chỉ được phép phục vụ tối đa sáu năm, năm thứ bảy phải cởi trói phóng thích hoàn toàn.', explanation: 'Dù bối cảnh cổ đại có hình thái nô lệ, đạo luật Môsê tạo sự kiện xuất chúng nhân đạo khi giới hạn chu kỳ hầu hạ và chăm lo nhân thân.' },
    { answer: 'PHONGTHICH', clue: 'Việc trao trả quyền tự do thiết thực cho người nô bộc Híp-ri khi họ đã làm việc qua trọn vẹn giới hạn hầu hạ phục vụ.', explanation: 'Hành động phóng thích nhắc nhở cội nguồn lịch sử thiêng liêng vì dân Híp-ri đã từng được chính Chúa cứu tháo đứt mọi cùm rào Ai Cập.' },
    { answer: 'XUXO', clue: 'Hành động đánh đấm gây họa cho thai phụ sẩy thai sẽ bị phán luật trừng phạt nghiêm bằng việc sinh đền sinh mạng.', explanation: 'Luật bồi thường án sẩy thai khẳng định cái nhìn trân quý bảo lưu sự sống bào thai trong dạ mẫu chứ không bao giờ xem rẻ tính mệnh cỏn con ấy.' },
    { answer: 'DATRAN', clue: 'Sự vụ rơi đá trần hay bò ngoắc bất ngờ húc chết người vô ý đột ngột, luật sẽ khoan dung miễn án tính tử đối đãi chủ nhà bớt oan uổng.', explanation: 'Sự phân cấp luật rõ rệt đối trọng cách cố sát lén lút và mảng ngộ sát thiếu mong đợi đã cấu thành tinh minh văn minh lề luật cực sâu sắc.' },
    { answer: 'MAT', clue: 'Bộ phận thị giác mà giả dụ có người ác tâm cố tình phá hỏng của nhãn người khác, sẽ phải lãnh bồi thường đối chọi tương ứng.', explanation: 'Luật trả thù cân xứng (Lex Talionis) xét về tính tích cực mang giá trị cao trào ngăn chặn băm bổ tàn dư vòng xoáy trả miếng khát máu luẩn quẩn vô độ.' },
    { answer: 'RANG', clue: 'Thứ cắn nhai bị vỡ bởi nắm đấm, và khi người chủ quyền lạm đánh gãy mất bộ phận này của nô lệ thì bắt buộc tự ý giải thoát thân nhân cho kẻ đó rời đi.', explanation: 'Đòn giải đáp tự do bù bão chiếc răng lụi là chuẩn mực tiến cấp thi hành bảo hành sự toàn năng thân xác cho chư kẻ hạ dân yếm thế dưới ách chủ.' }
  ]}
];
