module.exports = [
  {id:11,theme:'Mầu Nhiệm Giáng Sinh',words:[
    {answer:'GIESU',clue:'Đấng Cứu Thế giáng trần hạ sinh khó nghèo nơi Bêlem, mang lấy xác phàm để đem ơn cứu độ cho nhân loại.',explanation:'Chúa Giêsu là Ngôi Hai Thiên Chúa Nhập Thể. Ngài sinh ra nơi thấp hèn tột cùng để nâng vớt con người sa ngã lên địa vị Thiên Chúa.'},
    {answer:'BELEM',clue:'Thị trấn nhỏ bé nghèo nàn thuộc miền Giuđê, nơi ứng nghiệm lời các tiên tri xưa về nơi vị Vua hòa bình chào đời.',explanation:'Bêlem có nghĩa là "Nhà Bánh". Việc Chúa sinh ra ở đây báo trước Ngài chính là Bánh Hằng Sống từ trời xuống nuôi dưỡng nhân gian.'},
    {answer:'MANGCO',clue:'Chiếc nôi êm ái đầu tiên của Hài Nhi Thánh, vốn chỉ là chiếc khay đựng rơm cỏ cho súc vật ăn giữa đêm đông giá.',explanation:'Máng cỏ mộc mạc làm nổi bật sự khiêm hạ tột cùng của Thiên Chúa, khi Vua Vũ Thụ lại chọn một nơi hang bò tăm tối làm chốn ngả đầu.'},
    {answer:'THIENTHAN',clue:'Đạo binh ánh sáng rực rỡ từ trời cao xuất hiện trong đêm, hợp xướng vang lừng bài ca "Vinh Danh Thiên Chúa".',explanation:'Sự hiện diện của các vị vinh thần chứng tỏ vinh quang Thiên Chúa đang tỏa sáng rạng ngời, đem bình an đến cho những người thiện tâm.'},
    {answer:'MUCDONG',clue:'Những người nghèo thức trắng đêm chăn chiên ngoài đồng hoang, lại là những vị khách danh dự đầu tiên đến viếng Chúa.',explanation:'Chúa Giêsu không chọn tỏ mình cho vua quan hay tu sĩ học giả mà là những kẻ du mục bé mọn, khẳng định Tin Mừng luôn ưu ái người nghèo.'},
    {answer:'BAVUA',clue:'Những bậc đạo sĩ uyên bác từ phương Đông xa xôi, vượt đường dài theo ánh sao mầu nhiệm đến dâng vàng, nhũ hương, mộc dược.',explanation:'Phái đoàn Ba Vua (Hiển Linh) đại diện cho các dân ngoại khao khát tìm kiếm chân lý, nay được ánh sáng Thiên Chúa dẫn dắt đến tôn thờ Đấng Cứu Thế.'},
  ]},
  {id:12,theme:'Bài Giảng Trên Núi',words:[
    {answer:'MOIPHUC',clue:'Tám tuyên ngôn mở đầu Bài giảng của Chúa Giêsu, đảo lộn hoàn toàn mọi tiêu chuẩn hạnh phúc vật chất của thế gian.',explanation:'Tám Mối Phúc Thật không phải là một bộ luật khô khan mà là chân dung đích thực của Chúa Giêsu, khơi dậy niềm vui vì có Chúa làm gia nghiệp.'},
    {answer:'MUOIDAT',clue:'Loại gia vị mặn mà Chúa ví von để gọi các môn đệ, căn dặn họ phải ướp mặn cho đời và bảo vệ sự thiện khỏi hư nát.',explanation:'"Anh em là muối cho đời". Người Kitô hữu phải mang vào xã hội vị đậm đà của tình yêu, nếu mất đi ý vị thì không còn tác dụng gì ngoài việc bị quăng ra ngoài.'},
    {answer:'ANHSANG',clue:'Thứ mà Chúa căn dặn không được thắp lên rồi lấy thúng úp lại, mà phải đặt trên giá cao chiếu soi cho mọi người trong nhà.',explanation:'"Anh em là ánh sáng thế gian". Ánh sáng đức tin không thể chịu giấu kín, mà phải tỏa sáng qua các việc lành để tôn vinh Danh Cha trên trời.'},
    {answer:'LAYCHA',clue:'Bản kinh tuyệt hảo dâng lên Thiên Chúa gồm bảy lời nguyện cầu thiết yếu, do chính Chúa Giêsu truyền dạy trên núi.',explanation:'Kinh Lạy Cha là "Bản tóm lược toàn bộ Tin Mừng". Gọi Thiên Chúa là "Abba - Cha ơi" thể hiện sự phó thác tột cùng và tình hiếu thảo của con cái.'},
    {answer:'YEUTHU',clue:'Lệnh truyền thách thức nhất của Chúa: không chỉ tha thứ mà còn phải yêu thương và thiết tha cầu nguyện cho kẻ thù.',explanation:'Điểm khác biệt cốt yếu của Kitô giáo là tình yêu vô điều kiện, tựa như Cha ban ánh sáng mặt trời soi chiếu kẻ ác cũng như người thánh thiện.'},
    {answer:'DATANG',clue:'Nền móng vững chãi vô song mà người khôn ngoan chọn để xây nhà, tượng trưng cho đức tin nghe và thực hành Lời Chúa.',explanation:'Nghe Lời Chúa mà không thực hành thì giống xây nhà trên cát, sẽ sụp đổ thảm thương. Nền đá tảng vững bền ấy chính là Đức Kitô và đạo lý của Ngài.'},
  ]},
  {id:13,theme:'Mầu Nhiệm Ba Ngôi',words:[
    {answer:'THIENCHUA',clue:'Đấng Tạo Hóa uy quyền muôn loài, nguồn gốc mọi sự, trọn vẹn sự thiện mỹ, duy nhất một bản thể nhưng có ba Ngôi Vị.',explanation:'Mầu nhiệm Một Chúa Ba Ngôi là trung tâm tuyệt đối của đức tin Kitô giáo, không thể khám phá bằng lý trí mà nhờ ơn Mạc khải của Chúa Giêsu.'},
    {answer:'CHUACHA',clue:'Ngôi Thứ Nhất uy nghiêm thánh thiện, Đấng thấu suốt mọi bí ẩn và yêu thương thế gian đến nỗi ban chính vị Con Một.',explanation:'Trong Kinh Tin Kính, Chúa Cha là Đấng Tạo Thành trời đất muôn vật hữu hình và vô hình. Mọi quyền năng bắt nguồn từ Ngài trong tình yêu vĩnh cửu.'},
    {answer:'CHUACON',clue:'Ngôi Hai chí thánh, Đấng từ trời ngự xuống, mặc lấy xác phàm và chịu đóng đinh thập giá để đền tội thay cho loài người.',explanation:'Đức Kitô mang trọn hai bản tính: Thiên Chúa thật và Người thật. Ngài là Tòa trung gian duy nhất nối kết ơn xót thương và sự cứu rỗi nhân loại.'},
    {answer:'THANHTHAN',clue:'Ngôi Ba Thiên Chúa, nguồn sống thiêng liêng, là ngọn lửa tình yêu sưởi ấm Hội Thánh và tác động quyền năng qua các bí tích.',explanation:'Được sai đến trong Lễ Hiện Xuống, Chúa Thánh Thần là Đấng Bảo Trợ, ban cho Giáo Hội Bảy Ơn để can đảm sống đạo và thấu hiểu chân lý vẹn toàn.'},
    {answer:'BOCAU',clue:'Hình ảnh của loài chim bé nhỏ mang sắc thái hiền hòa mà Chúa Thánh Thần đã mượn để ngự xuống trên Chúa Giêsu tại sông Giođan.',explanation:'Biểu tượng chim bồ câu gắn liền với sự bình an từ thời Nôê. Tại sông Giođan, Mầu Nhiệm Ba Ngôi lần đầu tiên được mạc khải một cách hiển linh.'},
    {answer:'TINKINH',clue:'Bản tuyên xưng đức tin oai hùng của cộng đoàn, đọc vang giữa Thánh Lễ Chúa Nhật để quả quyết niềm tin Một Chúa Ba Ngôi.',explanation:'Kinh Tin Kính đóng vai trò như một bản tóm lược mọi chân lý cốt lõi, soi sáng và bảo vệ đức tin của người Kitô hữu giữ vững lòng cậy trông.'},
  ]},
  {id:14,theme:'Năm Phụng Vụ',words:[
    {answer:'MUAVONG',clue:'Khoảng thời gian tĩnh lặng đầu năm phụng vụ khoác áo tím đợi chờ, gồm bốn tuần thắp nến chuẩn bị tâm hồn đón Chúa Giáng Sinh.',explanation:'Mùa Vọng không chỉ là hân hoan nhớ lại biến cố Bêlem mà còn khơi lên tâm tình tỉnh thức đợi chờ Đức Kitô quang lâm trong vinh quang ngày tận thế.'},
    {answer:'MUACHAY',clue:'Hành trình mùa chuyên chăm bốn mươi ngày mang đậm dấu ấn hoán cải, ăn chay và bố thí, dẫn lối tâm hồn bước lên đồi Canvê.',explanation:'Con số 40 nhắc nhở hành trình chịu cám dỗ trong hoang địa. Mùa Chay rèn luyện ý chí, thanh tẩy đam mê ngõ hầu xứng đáng cử hành mầu nhiệm Vượt Qua.'},
    {answer:'PHUCSINH',clue:'Biến cố khải hoàn rực rỡ uy linh nhất, khi màn đêm nhường chỗ cho ánh sáng vinh quang và quyền năng Chúa đánh bại thần chết.',explanation:'Mùa Phục Sinh kéo dài 50 ngày rực rỡ, được xem là trung tâm của Năm Phụng Vụ. Giáo Hội ngân vang khúc tấu Alleluia hân hoan đón mừng Chúa Sống Lại.'},
    {answer:'TUANTHANH',clue:'Bảy ngày linh thiêng tột bậc bắt đầu bằng Chúa Nhật Lễ Lá, đưa cộng đoàn tưởng niệm từng chặng đường khổ nạn ngót nghét can trường.',explanation:'Tuần Thánh hội tụ Tam Nhật Vượt Qua: Tiệc Ly thiết lập Thánh Thể (Thứ Năm), Tưởng niệm cuộc Thương Khó (Thứ Sáu), Yên Nghỉ (Thứ Bảy) và Phục Sinh.'},
    {answer:'LETRO',clue:'Nghi thức xức chút bụi rắc lên đỉnh đầu hoặc trán vào dịp Lễ Thứ Tư, khai mạc chặng đường sám hối Mùa Chay dốc lòng.',explanation:'Bụi tro tượng trưng cho kiếp phù vân ("Ngươi là bụi tro sễ trở về tro bụi"). Ái dụ này mời gọi con người ý thức tính mỏng giòn và thành tâm hối cải.'},
    {answer:'CANHTHUC',clue:'Đêm thao thức linh thiêng làm phép lửa thắp rực sáng cây Nến Phục Sinh khổng lồ, cất vang khúc Exultet ca ngợi Ánh Sáng vinh diệu.',explanation:'Đêm canh thức Vượt Qua là "Mẹ của mọi đêm lễ". Ánh sáng bừng lên phá tan bóng tối tử thần, minh chứng cho sự sống khải hoàn trỗi dậy từ huyệt mộ.'},
  ]},
  {id:15,theme:'Đời Sống Đức Tin',words:[
    {answer:'CAUNGUYEN',clue:'Việc nâng tâm hồn hướng lên cùng Thiên Chúa, là lúc chúng ta khiêm nhường thiết tha dâng lời tạ ơn hay lắng nghe Lời Ngài.',explanation:'Cầu nguyện là hơi thở của đời sống đức tin. Chúa Giêsu thường xuyên lánh mình vào những nơi thanh vắng để hiệp thông tĩnh lặng cùng Chúa Cha.'},
    {answer:'MANCOI',clue:'Lời kinh Kính Mừng êm ái kết xâu tràng hạt như muôn đóa đóa hồng kiều diễm yêu thương thơm ngát ngợi khen dâng Đức Mẹ.',explanation:'Đây là con đường chiêm ngắm các mầu nhiệm cuộc đời Chúa Giêsu qua lăng kính của Mẹ Maria, giúp tín hữu đạt được bình an tĩnh lặng giữa trần đời.'},
    {answer:'XUNGTOI',clue:'Bí tích thanh tẩy dọn sạch cõi lòng, gột bỏ nhơ nhớp tội tình, đem lại ơn tha thứ và phục hồi hòa giải sâu sắc cùng Thiên Chúa.',explanation:'Nơi đây dung chứa lòng thương xót vô song độ lượng của Ngài, sẵn sàng ôm ấp vỗ về chữa lành những vết sẹo do lầm lỗi vô ơn khi con người thống hối.'},
    {answer:'THANHLE',clue:'Hiến tế cực thánh hiện tại hóa hành trình Thương Khó và Phục sinh của Chúa, nguồn mạch tuôn trào ân sủng nuôi dưỡng Hội Thánh.',explanation:'Trọng tâm của Thánh Lễ là Bàn tiệc Lời Chúa và Bàn tiệc Thánh Thể, nơi trời và đất giao thoa khi cộng đoàn chung tay hiến dâng mầu nhiệm vô hình.'},
    {answer:'ANNAN',clue:'Sự cắn rứt thống hối đau buồn vì đã dại khờ phạm tội xúc phạm Chúa, là điều kiện tiên quyết để nhận ơn đại xá tha thứ.',explanation:'Sự ăn năn trọn hảo phải xuất phát từ lòng kính mến Thượng Đế uy quyền trọn tốt trọn lành, chứ không chỉ vì nỗi kinh sợ ám ảnh những hình phạt hỏa ngục.'},
    {answer:'TINMUNG',clue:'Cốt lõi bốn quyển sách Tân Ước chan chứa hân hoan, rành rọt tường thuật về cuộc thế vinh quang kỳ diệu và huấn lệnh của Chúa Giêsu.',explanation:'Tin Mừng chứa đựng mạc khải trọn vẹn nhất của ơn thiêng Ngôi Lời, hằng ngày soi sáng trí suy định hướng sống dạt dào tình cốt lõi bác ái huynh đệ.'},
  ]},
  { id: 103, theme: 'XH 3: Bụi Gai Bốc Lửa', words: [
    { answer: 'BUIGAI', clue: 'Bụi cây kỳ lạ bốc cháy rừng rực trên núi nhưng ngọn lửa chói lọi không hề thiêu rụi cành lá.', explanation: 'Bụi gai cháy không tro tàn là hình tượng biểu trưng cho sự hiển linh tỏ mình uy hùng thiêng liêng siêu việt của Thiên Chúa.' },
    { answer: 'CHAY', clue: 'Hiện tượng ngọn lửa hừng hực bao trùm lấy bụi cây giữa vùng sa hoang khiến Môsê hiếu kỳ tiến lại coi xem.', explanation: 'Ánh lửa thu hút mạnh mẽ sự chú ý của Môsê, từ đó Thiên Chúa cất bổng tiếng vang gọi quyết định sai ông thực thi sứ vụ giải phóng dân Ngài.' },
    { answer: 'NUI', clue: 'Ngọn cao nguyên hoang vắng Khô-rếp, vinh dự là mảnh đất kỳ diệu Thiên Chúa lần đầu tiên uy quyền mặc khải chính mình cho Môsê.', explanation: 'Núi Khô-rếp (sau là Sinai) được xưng tán dõng dạc chính là ngọn núi của Thiên Chúa, tạo bối cảnh trọng đại đón chờ dòng lịch sử diễm phúc dân chúa.' },
    { answer: 'DUCCHUA', clue: 'Danh xưng uy lực mà chính Thiên Chúa từ đám lửa cất tiếng quyền uy tự xưng: "Ta là Đấng Hiện Hữu", nguồn cội nguồn mọi sự sống.', explanation: 'Danh xưng YHWH (Gia-vê) khẳng định dứt khoát hùng tráng rằng Đức Chúa là Đấng tự khởi nguồn mãi mãi hiện hữu vững chắc vĩnh quyền.' },
    { answer: 'THANH', clue: 'Mảnh đất uy linh dưới chân ông Môsê khiến vị ngôn sứ hoang mang vì lệnh phán thần thiêng phải gỡ cởi ngay giày dép vướng bụi trần.', explanation: 'Hành động nhỏ này nhắc người thế phàm nhân bé mọn nhớ rõ uy linh hiện thân chói dọi thiêng thánh tột độ từ Đức Chúa.' },
    { answer: 'THAO', clue: 'Hành vi tháo mở đôi hài dưới chân biểu đạt trọn vẹn lòng phủ phục quy hàng tôn vinh Nhan Thánh Thượng Đế đang ngự trị.', explanation: 'Bỏ dép khỏi chân trên nền đất thánh nhắc thế nhân mang một dấu chỉ xót xa thân phận yếu hèn để chầu chực nhún nhường phó thác triệt để.' }
  ]},
  { id: 104, theme: 'XH 4: Chúa Ban Quyền Năng', words: [
    { answer: 'GAY', clue: 'Vật dụng chăn cừu mộc mạc cầm tay của Môsê được Chúa ban quyền năng biến hóa thành con rắn.', explanation: 'Cây gậy chăn chiên bình thường trở thành bảo bối thi hành các phép lạ vĩ đại như rẽ nước Biển Đỏ, gõ vỡ tảng đá.' },
    { answer: 'RAN', clue: 'Loài bò sát đáng sợ mà cây gậy của Môsê hóa thành khi vứt xuống đất, khiến ông hốt hoảng bỏ chạy.', explanation: 'Phép lạ hóa rắn giúp Môsê có thêm niềm tin vững vàng để thuyết phục dân Israel và đối đầu với các pháp sư Ai Cập.' },
    { answer: 'PHONGHUI', clue: 'Căn bệnh đáng sợ nổi trắng toát trên bàn tay Môsê khi ông thọc tay vào ngực theo lệnh Thiên Chúa.', explanation: 'Dấu lạ bàn tay bị phong hủi rồi lại lành lặn chứng tỏ quyền năng chữa lành và tha bổng sinh mạng của Thiên Chúa.' },
    { answer: 'AHARON', clue: 'Người anh trai ruột thịt có tài ăn nói lưu loát được Chúa cắt cử làm người phát ngôn thay cho Môsê.', explanation: 'Sự xuất hiện của Aharon bù đắp cho điểm yếu ăn nói ấp úng của Môsê, thể hiện Chúa luôn ban ơn trợ giúp người Ngài chọn.' },
    { answer: 'KHEP', clue: 'Động tác khép miệng, mở miệng đều do quyền năng tạo hóa của Thiên Chúa, Ngài phán hỏi Môsê như thế.', explanation: 'Khi Môsê than phiền mình có tật nói ngọng, Chúa nhắc nhở Ngài mới là Đấng ban cho con người mọi giác quan.' },
    { answer: 'TINHIEU', clue: 'Ba phép lạ lớn được Chúa chỉ dạy để Môsê làm ra trước mặt toàn dân Israel nhằm chứng minh sứ mạng.', explanation: 'Những dấu lạ (tín hiệu) này là bằng cớ không thể chối cãi để dân Israel tin rằng Thiên Chúa của cha ông đã thực sự hiện ra.' }
  ]}
];
