module.exports = [
  {id:61,theme:'Các Thư Tín Trong Tân Ước',words:[
    {answer:'GIACOBE',clue:'Bức thư thực tế mạnh mẽ gióng lên hồi chuông cảnh tỉnh: đức tin gật gù suông miệng mà không có việc làm phụ họa là đức tin chết cứng.',explanation:'Thư thánh Gia-cô-bê nhấn mạnh việc sống Đạo, đập tan lối tự mãn chỉ cần tin nơi môi mép mà ngó lơ những người nghèo đói rách rưới đang kêu gào.'},
    {answer:'PHERO',clue:'Hai bức thư động viên an ủi dặt dìu của viên đá tảng Hội Thánh gởi đến các cộng đoàn đang gồng mình oằn lưng chịu bách hại thê sầu.',explanation:'Thánh Phê-rô dùng uyển ngữ sắc lẹm gọi người Ki-tô hữu là giống nòi được kén chọn, là hàng tư tế vương giả để vực dậy sĩ khí giữa muôn ngàn đòn roi.'},
    {answer:'GIOAN',clue:'Ba bức thư ngắn ngủi nhưng sâu thăm thẳm của vị tông đồ được sủng ái, liên tục lặp đi lặp lại điệp khúc hát ca Tình Yêu Thượng Đế.',explanation:'Ngài khẳng định rành rọt như đinh đóng cột: "Ai không yêu thương thì gã đó chẳng hề quen biết Chúa, vì bản chất Thiên Chúa đích thị là tình yêu".'},
    {answer:'GIUDA',clue:'Một trong những bức thư mỏng manh nhưng mang giọng gắt gao điệu sắc lẹm cảnh báo nguy cơ tà thuyết len lỏi tàn phá xé toạc bầy chiên.',explanation:'Thư Giu-đa mắng nhiếc không thương xót những kẻ trà trộn giả mạo dùng danh nghĩa tự do ân sủng để buông thả nuông chiều xác thịt tồi bại chướng tai.'},
    {answer:'KHAIHUYEN',clue:'Pho sách vĩ đại khóa chốt khép lại Kinh Thánh ngập ngụa biểu tượng thần bí về trận mạc khốc liệt và ngày khải hoàn vinh thắng của Chiên Con.',explanation:'Cuốn Khải Huyền do thánh Gio-an ghi lách trong cảnh lưu đày Pat-mốt, dệt mộng viễn cảnh Giê-ru-sa-lem thiên quốc giáng hạ vĩnh viễn quét sạch nước mắt.'},
    {answer:'MUCVU',clue:'Nhóm ba bức thư ngài Phao-lô gởi gắm cho Ti-mô-thê và Ti-tô nhằm phác thảo khuôn vàng thước ngọc quy mô cai quản huấn luyện Giáo Hội.',explanation:'Bức thư cặn kẽ trang bị chỉ nam tổ chức từ việc tuyển chọn Giám Mục, nết na linh mục đến đức hạnh phụ nữ, bảo ban đàn chiên nề nếp kỷ cương.'},
  ]},
  {id:62,theme:'Lời Chúa Trong Đời Sống',words:[
    {answer:'ANHSANG',clue:'Lời Thiên Chúa chiếu rọi rực rỡ dẹp tan bóng tối như ngọn đèn soi sáng bước chân ta đi khỏi vấp ngã thê thảm lọt hố trũng.',explanation:'Thánh vịnh 119 lặp lại ví von Kinh Thánh soi chiếu dẫn mồi đập vỡ mê lầm của thế gian, hướng đạo tâm hồn mò mẫm bấu víu vào chân ái vĩnh cửu.'},
    {answer:'KINHTHANH',clue:'Thư viện linh thánh vô giá hội tụ bảy mươi ba cuốn sách chứa đựng rạt rào hơi thở thần hứng linh diệu của Ngôi Ba Thiên Chúa.',explanation:'Từng vần từng chữ đan chéo không phải văn chương nhảm nhí trần phàm mà là bản hợp đồng máu thịt mạc khải, giúp con người lùng sục gặp được nhan Ngài.'},
    {answer:'LOICHUA',clue:'Thanh gươm hai lưỡi sắc bén chọc thủng vạch trần tâm can, vừa là gậy chăn dắt đe nẹt vừa là sữa thiêng vỗ béo tăng cường linh hồn.',explanation:'Không bị khóa cứng câm điếc trên trang giấy ngả vàng, Lời này mang quyền năng sống động cải tà quy chánh, lật đổ thói xấu cắm rễ ngoan cố.'},
    {answer:'DAVIT',clue:'Vua mục đồng thiện nghệ múa gảy đàn hạc xướng thắp lên những vần thơ cung oán lộng lẫy tột bậc bộc bạch cùng Đấng Tối Cao rành rọt.',explanation:'Chất thơ của vua Đa-vít bay qua hân hoan thắng trận ngất ngưởng, đáp xuống hố dơ hối hận giàn giụa và réo gọi kêu la đau đớn bị săn đuổi mướt mồ hôi.'},
    {answer:'SALOMON',clue:'Bậc quân vương trí dũng kiệt xuất từ khước xin xỏ vàng bạc mà nài xin ban ơn thông suốt khôn ngoan để lèo lái dân Chúa qua bĩ cực.',explanation:'Tác giả được gán ghép của sách Diễm Ca, Sách Châm Ngôn và Bảng Giảng Viên mang theo sự uyên bác rực sáng, dù cuối đường sa vào bẫy dâm thần ngoại.'},
    {answer:'MOSE',clue:'Vị trung gian lão luyện dũng mãnh mặt đối diện mạnh dạn đàm đạo với Thiên Chúa thâm tình như hai người bạn tâm giao tri kỷ rôm rả.',explanation:'Mô-sê mang lấy địa vị oai phong ghi chép lại Ngũ Thư gò bó lề luật, lãnh trọng trách vĩ cuồng kéo dân tộc nô lệ khỏi gông xiềng vua quan độc ác.'},
  ]},
  {id:63,theme:'Trung Tâm Hành Hương',words:[
    {answer:'VATICAN',clue:'Quốc gia thu nhỏ quyền lực tối cao nằm cuộn mình trong lòng Rô-ma, trung tâm đầu não sừng sỏ điều khiển con thuyền Giáo Hội toàn cầu.',explanation:'Với diện tích nhỏ hạt tiêu, quốc gia mầu nhiệm này chứa cất mồ thiêng tông đồ Phê-rô làm đá tảng nham thạch đập tung các sóng dữ bè rối đe dọa.'},
    {answer:'LODUC',clue:'Hang đá sần sùi tại biên giới Pháp trở thành suối nguồn tuôn ràn rạt phép lạ chữa lành từ bàn tay hiền mẫu nắn nót Đấng Vô Nhiễm.',explanation:'Hình ảnh thiếu nữ Béc-na-đét vạch đất cào bùn moi lên dòng suối nhãn lồng đập tắt bao miệng chê bai khinh bỉ bằng hằng tá phép khỏi bệnh ung thư kỳ tài.'},
    {answer:'FATIMA',clue:'Ngọn đồi đồng cỏ u buồn nghèo nàn Bồ Đào Nha rúng động chứng kiến phép lạ mặt trời nhảy múa điên cuồng trước bảy vạn đôi mắt há hốc.',explanation:'Đức Mẹ trao cho ba trẻ mục đồng bí mật chấn động cõi trần yêu cầu toàn thế giới dốc lòng đâm chồi sám hối lạy lục và siêng năng lần chuỗi hột Mân Côi.'},
    {answer:'GIERUSALEM',clue:'Thánh đô đẫm tụ dòng máu rát buốt xé da của Chúa, đích đến linh thiêng đứt ruột của mọi Kitô hữu rớt nước mắt khao khát viếng Mộ Trống.',explanation:'Chiếc rốn của vũ trụ, nơi giao thoa xung đột rạch mặt của các tôn giáo sừng sững bám trụ, và là đích điểm cuối cùng mạt thế Giê-ru-sa-lem thiên quốc gác vòm.'},
    {answer:'ATXIDI',clue:'Ngôi làng mộc mạc yên ả chon von giấu mình lận lẽ ở nước Ý, cái nôi tinh thần sản sinh ra vị thánh nghèo bám váy Mẹ hòa bình vĩ đại.',explanation:'Hành hương đến Át-xi-di là đằm mình trong hương thơm hoa cỏ tinh khiết tự trào của thánh Phan-xi-cô, rũ bỏ mùi tiền bạc đô hội nồng nặc ích kỷ.'},
    {answer:'LAVANG',clue:'Thánh địa rừng thiêng nước độc muỗi mòng tại Quảng Trị Việt Nam, nơi Đức Mẹ dịu hiền hiện ra trao nắm lá vằng xoa dịu giáo dân bách hại.',explanation:'Đức Mẹ La Vang an ủi đoàn chiên run rẩy ốm đói lẩn trốn dưới rặng cây lá vằng, hóa ban thuốc diệu kỳ cất gánh tủi nhục khổ đau vì giữ vững niềm tin cấm đoán.'},
  ]},
  {id:64,theme:'Không Gian Phụng Vụ',words:[
    {answer:'DENTHO',clue:'Tòa kiến trúc kiêu kỳ nguy nga trên đồi Xi-on bị tàn phá trơ tru trọc lóc, từng là Trái Tim mạ vàng nhịp đánh tự hào độc nhất dòng dõi Do Thái.',explanation:'Đền Thờ Giê-ru-sa-lem thuở xưa là mấu chốt quy tụ các nghi lễ súc vật đẫm máu. Ngày nay, Đền Thờ thực sự không do tay phàm xây cất chính là Mình Máu Chúa.'},
    {answer:'NHATHO',clue:'Mái nhà chung che chở thiêng liêng rợp bóng ân sủng mát rượi, nơi gia đình giáo xứ tấp nập quy tụ hằng tuần để đập chung một nhịp thở hân hoan.',explanation:'Nhà Thờ vươn cao tháp chuông chập tiếng nhắc nhở trần thế hối hả ngưng trệ bâu bám tiền bạc để quây quần lại bẻ bánh chia rượu tình huynh đệ sống sượng.'},
    {answer:'BANTHO',clue:'Khối đá cẩm thạch vững chãi đặt ngay chính giữa gian Thánh uy nghiêm, bệ phóng dâng lên hiến lễ cực Thánh phác họa trọn vẹn lại bàn tiệc đồi Sọ.',explanation:'Linh mục ôm lấy hôn lên Bàn Thờ lúc bắt đầu dâng lễ vì Bàn Thờ biểu tượng trượng phu cho chính Chúa Kitô là đá góc tường xẻo nát thân hiến cho đời.'},
    {answer:'NHATAM',clue:'Chiếc két an toàn bằng vàng mọc sừng sững tỏa đèn sáng choang lam ngọc đỏ rực, ngai tọa thiêng liêng chôn giấu cất bánh Trường Sinh nuôi dư bầy chiên.',explanation:'Tâm điểm tĩnh lặng tót vời của mọi nhà thờ. Có Bánh Thánh ngự nơi Nhà Tạm, ngôi thánh đường không còn là khối gạch rỗng nữa mà là trạm xá ẵm bồng.'},
    {answer:'CUNGTHANH',clue:'Khu vực trang trọng tách biệt cao ngảnh hơn gian nghênh ngang dành cho giáo dân, nơi linh mục khoác tế phục và khói hương trầm nghi ngút lượn sải.',explanation:'Ranh giới phân biệt nhưng không chia rẽ này ám chỉ tráng kiện sự dâng kỉnh sùng mộ, lôi kéo con mắt tín hữu quy về tâm điểm tạ ơn huyền nhậm màu nhiệm.'},
    {answer:'GHEQUY',clue:'Băng ghế gỗ trang bị sẵn bọc tấm đệm lót êm nhung nhúc để tín hữu hạ gối sấp mình ngã rạp phục lạy tôn vinh chói lọi trước sự huy hoàng của Thánh Thể.',explanation:'Cử chỉ gập gối nhún nhường bãi bỏ lòng kiêu căng cứng cổ, rập đầu tuyên xưng phụng tự rằng chỉ duy có một Thiên Chúa đáng được vinh quang thùy mị thần phục.'},
  ]},
  {id:65,theme:'Dòng Lịch Sử Cứu Độ',words:[
    {answer:'ADAMEVA',clue:'Cặp vợ chồng khởi thủy ngây dại được nặn hình tạo dáng từ bụi đất gân guốc sướng rơn xương sườn, đánh trơ đánh trát mất áo choàng ân sủng màng mộng.',explanation:'Nghe rỉ tai xúi bậy tà khạo ăn trái táo cấm, hai tổ tiên mang tội kiêu căng phì trướng nén rứt lật nhào ân huệ rực rỡ thuở sơ khai gieo rắc tủi nhục ngàn đời.'},
    {answer:'NOE',clue:'Bậc tổ phụ đóng mộc con tàu khổng lồ vĩ đại vớt vát muông thú lúc nhúc và tám mạng sót lóp ngóp sau khi cơn thịnh nộ đại hồng thủy sủi bọt rút cạn tơi tả.',explanation:'Con tàu bềnh bồng tránh nạn trôi dạt vô định là hình bóng tiên vàn của Giáo Hội thu vén muôn dân tránh khỏi cơn hồng thủy xé toang tội ác dìm đuối trầm luân.'},
    {answer:'AICAP',clue:'Đất nước hùng cường kiêu ngạo dùng roi vọt bóc lột nhẫn tâm ép dân Chúa đập đá làm gạch rền rĩ suốt bốn trăm năm rên xiết tàn tạ cay đắng.',explanation:'Nhà nô lệ là biệt danh khét lẹt của Ai Cập. Hình bóng giã từ trút bỏ mọi thứ trốn chạy lúc sẩm tối biểu đạt sự dứt khoát rũ rượi chối từ kiếp nô lệ bùn thối tối tăm.'},
    {answer:'XINAI',clue:'Ngọn đỉnh đồi hùng vĩ nghi ngút khói sấm chớp nổ đoàng đoàng chát chúa rú rít, nơi Chúa chốt hạ ban Luật Mười Răn và thề thốt đẫm máu gò ép với Ít-ra-en.',explanation:'Giao ước khắc ruột trên tấm đá thể hiện trật tự tình yêu đắp móng vững bền, đòi hỏi nghiêm nhặt lòng trung thành trơ khấc trước Đấng đã đưa tay cứu vớt.'},
    {answer:'BABYLON',clue:'Đế quốc sừng sỏ ác trọc kéo lê nức nở dân Chúa đi biệt xứ vùi dập xót xa, làm kiếp xích chân lưu đày buồn thảm mòn mỏi nhớ về đồi cố hương.',explanation:'Khóc bên dòng sông Ba-by-lôn là chuỗi ngày tăm tối thắt nghẹt nhất của tuyển dân tước đoạt nước mắt để thanh tẩy thói vô ơn bạc nghĩa lật mặt thờ thần rởm khét lẹt.'},
    {answer:'MACABE',clue:'Những người con gia tộc lẫm liệt ôm đao phất cờ khởi nghĩa xua đuổi chém giết quân xâm lược ngáo ngơ nhằm tẩy uế giành lại đền thánh sáng chói.',explanation:'Sự kiên cường hùng bạo thà bị ném vạc dầu đục nhổ móng chứ quyết lòng chẳng hề xơi thịt heo ô uế đánh gục mọi cuồng nộ uy quyền đập đục ngoại giáo ác nghiệt.'},
  ]},
  { id: 123, theme: 'XH 22: Luật Về Tài Sản', words: [
    { answer: 'TROM', clue: 'Kẻ lén lút khoét vách ban đêm bưng đồ bị gia chủ bắt quả tang đánh chết thì chủ nhà sẽ được trắng án tha mạng tọi.', explanation: 'Quy định này cho phép quyền phòng vệ chính đáng bảo vệ tài sản và tính mạng vào ban đêm khi khó phân biệt mức độ nguy hiểm.' },
    { answer: 'BOITHUONG', clue: 'Nghĩa vụ đền bù hao hụt gấp đôi gấp ba khi vô cớ làm thiệt hại súc vật hay thả rông gia súc sang ăn lúa ruộng đồng nước xóm.', explanation: 'Đền bù công bằng nhằm khôi phục thiệt hại kinh tế gây ra cho nạn nhân, nhấn mạnh trách nhiệm bảo vệ an ninh cộng đồng.' },
    { answer: 'GOABUA', clue: 'Đối tượng phụ nữ mất chồng khốn nhùng yếu đuối, Chúa tuyệt đối nghiêm cấm việc bóc lột ức hiếp họ không thương tiếc.', explanation: 'Cùng với trẻ mồ côi và ngoại kiều, góa phụ là những người thuộc diện ưu tiên bảo bọc của chính Đấng Tối Cao bênh vực.' },
    { answer: 'KHOANCAT', clue: 'Hành vi cho người túng khấn bất bách vay mượn nhưng lại ác tâm kèm theo lãi suất cắt cổ, bị cấm tiệt trong dân Chúa.', explanation: 'Cấm vay nặng lãi nhằm củng cố tình liên đới nội khối huynh đệ, không để người nghèo bị dồn vào cảnh bần cùng bán vợ đợ con.' },
    { answer: 'AOKHOAC', clue: 'Tài sản cầm cố phòng thân duy nhất phải được mau chóng đem trả lại cho con nợ trước lúc mặt trời lặn cho họ còn đắp che thân.', explanation: 'Quy tắc cầm áo khoác thể hiện lòng từ bi tuyệt đỉnh vì áo là vật dụng duy nhất che chở người nghèo khỏi cái lạnh buốt đêm sa mạc.' },
    { answer: 'XUCDON', clue: 'Hành vi chóp chép sỉ nhục lăng đàm nguyền rủa các vị lãnh tụ đang cầm chịch hay đay nghiến phỉ báng Thiên Chúa đều bị trừng trị rát tay.', explanation: 'Cấm xúc phạm lãnh đạo nhằm bảo vệ trật tự nhà nước ổn định sơ khai khỏi sự phiến loạn xúi giục ngông cuồng làm rã đám cộng đồng.' }
  ]},
  { id: 124, theme: 'XH 23: Luật Lễ Hội', words: [
    { answer: 'THIENTE', clue: 'Việc thiên vị ác ý kẻ nghèo hèn tại phiên toà hay dua nịnh hùa theo đám đông vu oan làm chứng dối đều bị Chúa cấm kỵ.', explanation: 'Công lý không thuộc phe số đông cũng không thiên vị sự nghèo khó. Công lý là sự mù lòa mù tịt xét xử trên sự thật trần trụi.' },
    { answer: 'NGOAIKIEU', clue: 'Thành phần rách rưới tha hương dân lạ, được luật bắt dân Israel đối đãi nhân từ vì bản thân họ cũng từng lưu đày lang thang vất vưởng.', explanation: 'Kinh nghiệm cay đắng nô lệ thời Ai Cập trở thành bài học đạo đức nền tảng để đối xử cảm thông tôn trọng với những di dân nhập nội.' },
    { answer: 'BAYNAM', clue: 'Định kỳ năm Thánh bắt buộc đất ruộng cày cấy phải được đình chỉ bỏ hoang nỏn nà không gặt hái nhằm cho người nghèo thu nhặt tự do.', explanation: 'Năm nghỉ đất (Sabatical year) là thời gian đất đai phục hồi và người nghèo tận hưởng hoa màu tự sinh, phá bỏ sự tư hữu ích kỷ.' },
    { answer: 'BA', clue: 'Số lượng các dịp đại lễ cốt lõi trong năm mà mọi người nam giới đêu phải khăn gói trẩy lên chầu chực nhan thánh Đức Chúa.', explanation: 'Ba lễ lớn (Bánh Không Men, Mùa Gặt, Lều Tạm) là sợi dây thừng gắn kết cả chiều dài lịch sử tôn giáo và chu trình kinh tế thu hoạch nông nghiệp.' },
    { answer: 'MUAGAT', clue: 'Lễ dâng tiến hoa trái đầu mùa thơm ngọt ngào tươm mướt nhất của đồng ruộng mà Thiên Chúa thương ban sau vụ mùa bội thu.', explanation: 'Lễ Các Tuần (Ngũ Tuần muộn màng) là lễ Tạ Ơn biểu thị lòng biết ơn vâng phục trước Đấng là chủ tể thực sự ban chồi nẩy lộc cho vùng đất.' },
    { answer: 'THIENTHAN', clue: 'Sứ giả uy mãnh được Đức Chúa dặn phái đi trước mở đường canh gác dân Chúa tiến hùng hồn vào chiếm cứ xứ sở miền Đất Hứa cheo leo.', explanation: 'Thiên thần đi trước là minh chứng sự hướng dẫn vô hình của Chúa vung kiếm giải quyết mọi khó nhọc trở ngại quân sự mà họ đang cuống cuồng lo sợ.' }
  ]}
];
