module.exports = [
  {id:36,theme:'Phán Xét Cuối Cùng',words:[
    {answer:'PHANXET',clue:'Hành động tối cao và dứt khoát của Chúa Kitô khi Ngài phán xử mọi tư tưởng và việc làm của con người.',explanation:'Sẽ có hai cuộc phán xét: phán xét riêng ngay khi linh hồn lìa xác, và phán xét chung công khai vào ngày tận thế để tỏ lộ công lý trọn vẹn của Thiên Chúa.'},
    {answer:'THIENDANG',clue:'Tình trạng hạnh phúc tuyệt hảo, nơi các thánh được chiêm ngưỡng dung nhan Thiên Chúa nhãn tiền.',explanation:'Thiên Đàng không phải là một nơi chốn vật lý, mà là tình trạng hiệp thông tình yêu viên mãn trọn vẹn với Ba Ngôi Thiên Chúa.'},
    {answer:'HOANGUC',clue:'Bản án đau đớn tột cùng dành cho những kẻ kiên quyết chối từ tình yêu Chúa đến hơi thở cuối cùng.',explanation:'Thiên Chúa không an bài cho ai sa vào Hỏa ngục. Đây là hệ quả tự nhiên của một quyền tự do cố tình cự tuyệt lòng thương xót vô biên.'},
    {answer:'LUYENNGUC',clue:'Trạng thái thanh luyện gột rửa những vết nhơ tội lỗi còn sót lại trước khi xứng đáng bước vào Nước Chúa.',explanation:'Tình yêu trong trắng đòi hỏi linh hồn phải rực rỡ không tì vết. Luyện ngục là ân sủng gột rửa cuối cùng, chan chứa niềm hy vọng chắc chắn.'},
    {answer:'PHUCSINH',clue:'Sự kiện oai hùng khi thân xác của mọi người được chỗi dậy sống lại kết hợp với linh hồn trong ngày thế mạt.',explanation:'Tin vào sự sống lại của thân xác là cốt lõi Kitô giáo. Xác phàm yếu đuối mục nát, sẽ được Thiên Chúa phục hồi thân xác vinh quang.'},
    {answer:'QUANGLAM',clue:'Sự ngự đến vinh quang tráng lệ của Con Người để khép lại dòng chảy lịch sử của toàn nhân loại.',explanation:'Ngày Quang Lâm (Parousia) là ngày Đức Kitô trở lại. Vì không ai biết trước ngày giờ đó, nên thái độ của tín hữu luôn phải là thức tỉnh đợi chờ.'},
  ]},
  {id:37,theme:'Các Nhân Đức',words:[
    {answer:'DUCTIN',clue:'Nhân đức đối thần giúp chúng ta vững vàng phó thác hoàn toàn vào những chân lý Thiên Chúa đã mặc khải.',explanation:'Tin không đơn thuần là đồng ý của lý trí, mà là sự hiến thân cá nhân hoàn toàn phó thác cuộc đời mình cho sự quan phòng của Ngài.'},
    {answer:'DUCCAY',clue:'Chiếc mỏ neo chắc chắn giữ linh hồn không bị tuyệt vọng chìm đắm giữa đại dương đau khổ trần gian.',explanation:'Đức Cậy hướng nếp sống chúng ta về phần thưởng Thiên Đàng, giúp ta vững lòng vượt qua thử thách vì tin chắc Chúa luôn thành tín.'},
    {answer:'DUCAI',clue:'Cốt tủy của lề luật, đòi hỏi chúng ta phải yêu mến Thiên Chúa hết lòng và yêu tha nhân như yêu chính mình.',explanation:'Không có Đức Ái, mọi lề luật đều trống rỗng. Thánh Phaolô đã khẳng định: Dù có hiến cả thân mình mà không có tình yêu, cũng trở nên vô ích.'},
    {answer:'KHONNGOAN',clue:'Nhân đức trụ cột giúp lý trí nhạy bén phân định đâu là điều thiện thực sự để lựa chọn phương tiện đúng đắn.',explanation:'Khôn ngoan là kim chỉ nam của các nhân đức. Nó định hướng ta hành động để không bị ảo tưởng thế tục lừa gạt và làm điều đẹp ý Chúa.'},
    {answer:'DUNGCAM',clue:'Sức mạnh nội tâm siêu nhiên giúp các vị tử đạo vững vàng chấp nhận hy sinh làm nhân chứng cho đức tin.',explanation:'Dũng cảm giúp ta sẵn sàng vượt qua sợ hãi và chấp nhận nghịch cảnh nề hà do lòng trung thành với chân lý Phúc Âm.'},
    {answer:'TIETDO',clue:'Nhân đức luân lý giúp chế ngự sức hút của những đam mê nhục dục và giữ mức độ chừng mực.',explanation:'Nhân đức Tiết độ làm chủ các giới hạn thèm khát ăn uống và sắc dục, bảo đảm phẩm giá cao quý của con người trước bản năng xác thịt.'},
  ]},
  {id:38,theme:'Nhân Vật Cựu Ước',words:[
    {answer:'MOSE',clue:'Vị lãnh tụ vĩ đại cầm gậy rẽ nước Biển Đỏ, dẫn dắt dân Chúa thoát khỏi ách nô lệ Ai Cập.',explanation:'Môsê là vị ngôn sứ lớn nhất của thời Cựu Ước, người đối thoại với Chúa tại núi Sinai và lãnh nhận bản Mười Điều Răn.'},
    {answer:'IXAAC',clue:'Người con hiến tế sẵn sàng chịu trói đặt lên đống củi trong thử thách đức tin của người cha.',explanation:'Sự dâng mình vâng phục mẫu mực của Ixaác là hình ảnh báo trước tuyệt hảo về hiến lễ tình nguyện của Chúa Giêsu trên Thập Giá.'},
    {answer:'GIACOP',clue:'Vị tổ phụ đã vật lộn suốt đêm cùng thiên thần, sau đó được vinh dự đổi tên thành Israel.',explanation:'Giacóp, mang danh xưng mới là Israel, đã sinh ra mười hai người con trai để làm cội rễ lập ra mười hai chi tộc dân Chúa.'},
    {answer:'GIOSUE',clue:'Vị tướng dũng mãnh kế nhiệm Môsê dẫn dắt dân băng qua sông Giođan và tiến vào miền Đất Hứa.',explanation:'Giôsuê dẫn dắt đạo binh Israel băng qua khúc sông Giođan cạn khô và chinh phục Giêricô bằng lòng vâng phục lề luật.'},
    {answer:'TOBIA',clue:'Người thanh niên hiếu thảo được thiên sứ Raphaen bạn đường đồng hành để tìm phương thuốc chữa mắt cho người cha.',explanation:'Câu chuyện kỳ diệu của Tôbia nhấn mạnh sự quan phòng mầu nhiệm của Chúa dành cho những gia đình sống trung thành với luật Chúa.'},
    {answer:'MACABE',clue:'Gia tộc kháng chiến anh hùng thà chịu tử đạo nhằm bảo vệ lề luật cha ông chứ không chịu ăn thịt ô uế.',explanation:'Sự kiên vững của những anh em dòng dõi Macabê tử đạo nêu rõ niềm tin về sự sống lại, cũng là nền tảng cầu nguyện cho người đã khuất.'},
  ]},
  {id:39,theme:'Bảy Mối Tội Đầu',words:[
    {answer:'KIEUNGAO',clue:'Cội rễ của mọi tội lỗi, là thói kiêu căng phụ bạc muốn gạt bỏ và đặt mình lên ngang hàng Thiên Chúa.',explanation:'Sự sa ngã của thiên thần Luxiphe cũng vì cớ kiêu ngạo. Thói xấu này phá hủy sự khiêm nhường mỏng giòn, cho mình là trung tâm.'},
    {answer:'HATIEN',clue:'Lòng tham lam quá bám víu tôn thờ tiền của trần thế, trở thành nô lệ cho những vật chất hữu hạn.',explanation:'Chúa đã phán không ai có thể làm tôi hai chủ. Thói tham lam vắt kiệt tình thương ái tuất, khiến con người bủn xỉn chà đạp lên người nghèo.'},
    {answer:'GHENTI',clue:'Tính xấu gặm nhấm tâm hồn với sự buồn bực xót xa trước những thành công hay phần phúc của anh em người khác.',explanation:'Ghen tị là hạt giống của sự ghen ghét. Xưa kia do ghen tức nhẫn tâm, Cain đã ruồng giết Abel nương vì của lễ được Chúa nhận.'},
    {answer:'DAMO',clue:'Sự ham muốn buông thả tìm kiếm các khoái lạc xác thịt lỗi nghịch khiết tịnh và phẩm giá đền thờ của con người.',explanation:'Tội dâm ô làm phá vỡ nhân phẩm. Nó lăng nhục và coi thường ân huệ tình yêu truyền sinh mà Thiên Chúa đã mời gọi trong bậc hôn nhân thánh.'},
    {answer:'GIANDU',clue:'Cơn nóng giận ác cảm bùng cháy thiếu tự chủ, dễ dẫn đến xúc phạm người khác bằng đay nghiến lăng mạ sỉ vả.',explanation:'Cơn tức giận xua đuổi sự bình an trong tâm hồn. Chúa dạy ai mắng chửi hận anh em mình thì mang trọng tội trước Nhan Hóa Công.'},
    {answer:'LUOIBIENG',clue:'Sự chểnh mảng lười nhác buông xuôi bổn phận, đặc biệt là dửng dưng trễ nải với các trách nhiệm thờ phượng báo hiếu Thiên Chúa.',explanation:'Lười biếng tâm linh là một căn bệnh liệt kháng thiêng liêng, khiến linh hồn chết mòn vì dửng dưng không thiết tha với tình yêu của Chúa.'},
  ]},
  {id:40,theme:'Lời Kinh Phụng Vụ',words:[
    {answer:'VINHDANH',clue:'Bài ca thiên thần vang lên rạng rỡ bầu trời đêm Giáng Sinh, nay được Hội Thánh long trọng hát xướng vào các đại lễ.',explanation:'Kinh Vinh Danh (Gloria) mang tiết tấu vui mừng để tung hô Ba Ngôi, nguyện xin Chúa ban tràn bình an xuống những người Chúa thương.'},
    {answer:'ALELUIA',clue:'Lời tung hô hân hoan có nguồn gốc Do Thái giáo, được Hội Thánh cất lên rộn rã trước khi công bố đoạn Phúc Âm.',explanation:'Alleluia mang ý nghĩa Hãy ngợi khen Chúa bằng niềm vui Tin Mừng Phục Sinh, thường xuyên được tạm ngưng cất tiếng suốt trong Mùa Chay Thánh.'},
    {answer:'NGOIKHEN',clue:'Bài ca tuyệt diệu Đức Mẹ cất lên để tán dương quyền năng Thiên Chúa trong biến cố đến thăm điền gia đình bà Êlixabét.',explanation:'Kinh Magnificat lột tả chương trình nghịch lý của Chúa so với nhận thức trần thế: hất đổ kẻ hùng mạnh và suy tôn người khiêm nhường túng nghèo.'},
    {answer:'SANGDANH',clue:'Lời kinh súc tích và ngắn gọn dùng để nguyện bái lạy suy tôn mầu nhiệm trói lòa Một Chúa Ba Ngôi vĩnh cửu.',explanation:'Dù chỉ là vần ngắn đọc vội, nhưng kinh Sáng Danh đã khẳng định vinh hiển vương quyền từ thuở xa xưa cho đến hiện tại và nối dài muôn đời.'},
    {answer:'THUNHAN',clue:'Lời kinh sám hối kèm động tác ăn năn đấm ngực xưng thú xưng nhận mọi lỗi lầm để thanh tẩy trước cử hành Thánh Lễ.',explanation:'Nghi thức sám hối ở đầu giờ thiêng liêng chắt nhắc nhớ tình trạng bất túc yếu hèn của chúng ta đáng tội để được rước Mình Máu Chúa đoái thương.'},
    {answer:'KINHMUNG',clue:'Lời chào lịch sử vượt nhịp thời gian của vị thiên sứ ngỏ lời kính viếng Mẹ đem lại niềm ơn phúc cho trọn nhân thế.',explanation:'Sự kiện truyền tin gửi gắm Ave Maria báo sự khởi đầu của một kỷ nguyên cứu độ xua tan mây mù tội lỗi từ xưa của Evà nguyên tổ.'},
  ]},
  { id: 113, theme: 'XH 13: Dâng Con Đầu Lòng', words: [
    { answer: 'DAULONG', clue: 'Theo luật định, mọi người con trai hoặc con vật đực sinh ra đầu tiên đều phải được thánh hiến cho Thiên Chúa.', explanation: 'Luật thánh hiến con đầu lòng giúp người Israel ghi nhớ việc tạ ơn Thiên Chúa đã cứu chuộc mạng sống họ đêm vượt qua khỏi Ai Cập.' },
    { answer: 'COTMAY', clue: 'Đám mây kỳ diệu hiển hiện để dẫn đường bước đi ban ngày cho dân Chúa tiến trong hành trình tiến về Đất Hứa.', explanation: 'Cột mây là biểu hiện sự đồng hành an ủi từ Thiên Chúa, dùng để che chở dòng người khỏi cái nóng oi ả nơi cõi sa mạc.' },
    { answer: 'COTLUA', clue: 'Cột ánh sáng rực rỡ uy nghi chiếu soi giữa tăm tối để dẫn lối đi bước lữ hành vào ban đêm.', explanation: 'Cột lửa soi sáng bước chân vào ban đêm, cho phép toàn dân tiếp tục cuộc lữ hành không ngơi nghỉ để trốn sự truy kích của Pharaô.' },
    { answer: 'GIUSE', clue: 'Vị tổ phụ nổi tiếng năm xưa, người mà khi xuất hành đi Môsê đã luôn mang theo hài cốt trọn vẹn.', explanation: 'Mang theo hài cốt Giuse là việc tuân giữ lời hứa và niềm hy vọng từ thời các tổ phụ để ngõ hầu an táng ngài trong Đất Hứa.' },
    { answer: 'NGAY', clue: 'Khung thời gian Chúa dùng cột mây che bóng nóng gay gắt, giúp dân nhịp bước an toàn nơi hoang địa.', explanation: 'Dù ban ngày hay ban đêm luân chuyển, sự bảo bọc yêu thương và hồng ân của Chúa chưa từng lìa bỏ dân Ngài.' },
    { answer: 'DEM', clue: 'Lúc sa mạc buông hơi lạnh tối tăm, đoàn người tị nạn vẫn vững vàng tiến bước nhờ sự soi sáng kỳ diệu của cột lửa.', explanation: 'Bất kể ban ngày nóng nực hay ban đêm rét buốt cản trở, sự hiện diện của Thiên Chúa ban luôn mang lại niềm an ủi tuyệt đối.' }
  ]},
  { id: 114, theme: 'XH 14: Vượt Biển Đỏ', words: [
    { answer: 'BIENDO', clue: 'Khối nước sừng sững dâng lên cản trở ngõ thoát khi phía sau là đồn binh Ai Cập đang truy đuổi.', explanation: 'Biển Đỏ không còn là rào cản đường cùng, nó trở thành sân khấu lịch sử vĩ đại tỏ bày quyền năng cứu độ siêu việt của Thiên Chúa.' },
    { answer: 'GIODONG', clue: 'Cơn gió lớn tự nhiên được Thiên Chúa thổi tới suốt đêm dồn nước sang hai bờ rẽ thành lối đi ráo bộ.', explanation: 'Cơn gió đông được Thiên Chúa dùng như công cụ uy quyền vạch ra con đường cứu thoát dân Chúa bảo toàn mạng sống diệu kỳ.' },
    { answer: 'COXE', clue: 'Cỗ chiến xa kiêu ngạo của quân Ai Cập truy sát gặp phải bùn mắc kẹt sa lầy đọng lại giữa lòng biển.', explanation: 'Chiến xa tự hào của đế chế Pharaô đâm ra vô dụng, trở thành nấm mồ chôn vùi quân đội kiêu ngạo dám làm trái thiên ý.' },
    { answer: 'BIENKHOI', clue: 'Nơi chôn vùi hàng ngàn binh lực Ai Cập tàn sát khi bức tường thế lực nước biển đột ngột sập xuống.', explanation: 'Cái chết của đạo quân truy lùng trong biển khơi biểu tượng việc dìm chết mọi tội ác gông cùm, giải thoát dân sống trong tự do.' },
    { answer: 'CHIM', clue: 'Cái kết trầm mình ngộp thở của binh đoàn Ai Cập khi dòng nước khép lại đổ ập trào dâng vùi lấp.', explanation: 'Sự kiêu ngạo của binh Ai Cập phải vong mạng dưới sức nước; dòng chảy giải thoát cho dân Israel lại hóa thành đòn phán xét quân thù.' },
    { answer: 'KHO', clue: 'Tình trạng ráo tạnh dưới đáy biển được ban cho dân Híp-ri băng ngang qua an toàn tẩu nạn.', explanation: 'Việc vượt bước dạo trên thềm cạn khô ráo vạch ra hình ảnh khải hoàn của sức mạnh Đức Tin, vượt qua tử thần tới bờ sống hiển vinh.' }
  ]}
];
