module.exports = [
  {id:56,theme:'Bốn Sách Tin Mừng',words:[
    {answer:'MATTHEU',clue:'Tác giả sách thứ nhất vốn là một viên chức thu thuế tham lam bị ruồng bỏ đã đứng phắt dậy nhẹ tênh đi theo tiếng gọi.',explanation:'Sách Mát-thêu đặc biệt hướng đến độc giả gốc Do Thái, trưng dẫn rành rọt hàng loạt lời sấm Cựu Ước để chứng minh xuất xứ hoàng tộc Đa-vít của Đấng Mê-si-a.'},
    {answer:'MACCO',clue:'Cuốn Phúc Âm lâu đời và gãy gọn cụt lủn nhất, mang nhịp điệu dồn dập hùng hục kể chuyện như một thước phim hành động cấp kì.',explanation:'Thánh Mác-cô ghi chép lại sinh động lời giảng hùng hồn của thánh Phê-rô, nổi bật với cụm từ "lập tức" lặp đi lặp lại dồn dập mô tả quyền năng xô lật phép lạ.'},
    {answer:'LUCA',clue:'Vị y sĩ uyên bác cầm cọ vẽ nên bức chân dung dung dị chắp vá nhất về sự nhân hậu của Chúa qua ngọn bút mượt mà ấm áp.',explanation:'Lu-ca được mệnh danh là người ghi chép Tin Mừng của xót thương, với những dụ ngôn kinh điển bất hủ rơi lệ như Người Cha Nhân Hậu và Người Sa-ma-ri tốt lành.'},
    {answer:'GIOAN',clue:'Người môn đệ Chúa cưng nựng rúc đầu vào ngực Thầy, chắp bút pho Phúc Âm cuối cùng chìm đắm trong chiều kích thần học thiên thượng.',explanation:'Sách Gio-an bay bổng cao vút như dáng hình chim đại bàng, không mải miết theo mạch thời gian mà xoáy sâu vào các bài thông điệp diễn từ vĩ đại "Ta là".'},
    {answer:'NHAPTHE',clue:'Hành trình hạ mình choáng váng khi Ngôi Lời vô biên quyền phép rũ bỏ ngai vàng rớt xuống trần khoác lấy xác phàm tuế toái rạn nứt.',explanation:'Tin Mừng thứ tư mở mang một thực tại chói lòa: Thiên Chúa vô hình làm người vỡ vụn, cắm lều ở giữa đám con cái trơ trụi để mở đường giao duyên thiên quốc.'},
    {answer:'TINMUNG',clue:'Bản giao hưởng rực rỡ vui sướng rộn rã nhất gồm bốn cuốn đầu Tân Ước, tường thuật sinh động ngất ngây cuộc đời và trăn trối của Chúa.',explanation:'Phúc Âm không phải là một quyển sách ru ngủ chết khô mà là sức mạnh bục vỡ của Thiên Chúa ập xuống cứu rỗi bất cứ kẻ nào mở rộng màng nhĩ đón nhận.'},
  ]},
  {id:57,theme:'Tuần Thánh Khổ Nạn',words:[
    {answer:'LELA',clue:'Cột mốc khai màn rạo rực Tuần Thánh khi dân chúng hò reo bứt nhành cây vẫy vùng trải áo bụi bặm, tung hô Vua Khải Hoàn cỡi lừa.',explanation:'Sự tưng bừng phô diễn ngất trời mang vị đắng chát xót xa khi chính đám đông tung hô vạn tuế này chẳng mấy chốc sẽ gân cổ gào xé đòi đóng đinh Người.'},
    {answer:'THUNAM',clue:'Đêm cực thánh đẫm xót xa chứa đựng Bữa Tiệc lịch sử, nơi Chúa khom lưng lấy chậu nước rửa chân tanh hôi chiên chóp bầy.',explanation:'Thứ Năm lập Bí Tích Thánh Thể và Chức Thánh Linh mục, đồng thời phanh phui bi kịch bán dóc phản trịch nộp thầy bằng một cái hôn lạnh ngắt kinh tởm.'},
    {answer:'THUSAU',clue:'Ngày đau xương buốt tủy bầu trời sập tối giữa trưa chót vót lúc ba giờ, khi Đấng Cứu Thế trút hơi thở cuối dằn vặt trên thập tự.',explanation:'Toàn thể Giáo Hội lặng ngắt sấp mình suy tôn mộc hình ô nhục đã hóa thân rực rỡ thành biểu tượng chiến thắng băm nát cổng ngục tử thần xích vây.'},
    {answer:'MOTRONG',clue:'Bằng chứng thinh lặng nhưng oai hùng tột đỉnh vào sáng sớm rạng đông ngày thứ nhất, khi tảng đá lấp cửa bị lăn lông lốc bật tung.',explanation:'Ngôi mộ vắng tanh khăn liệm xếp gọn gàng xóa nhòa mọi phỏng đoán thất bại ê chề mụn vụn, để lộ manh mối vô hình báo trước quyền năng hất tung thần chết.'},
    {answer:'PHUCSINH',clue:'Biến cố lật ngược thế cờ đập tan mọi vương triều thần chết tăm tối, đem lại mạch sống ánh bình minh khải hoàn bừng vỡ bất hoại.',explanation:'Chúa Kitô phục sinh không phải là một ma hồn bay lượn mà mang thương tích oằn oại in hằn thành dấu vết rạng rỡ khép lại lịch sử tủi nhục cứu nhân loại.'},
    {answer:'GIETSIMANI',clue:'Khu vườn vắt kiệt mồ hôi trộn lẫn giọt máu tuôn rơi rơi lấm tấm, nơi Chúa sấp mặt gào lên nài xin Cha cất chén đắng ngắt chua ngoa.',explanation:'Bỏ mặc các môn đệ ngáp ngắn ngáp dài đắm chìm ngủ gật, giờ phút cô đơn tột bực của Chúa gánh gồng cả mớ tội lỗi nhớp nháp nhân thế nện xuống tâm gí.'},
  ]},
  {id:58,theme:'Giai Đoạn Sáng Thế',words:[
    {answer:'BABEN',clue:'Ngọn tháp kiêu ngạo ngất ngưởng bị đánh sập chát chúa, tản mát chia rẽ ngôn ngữ loài người đang loay hoay muốn chòi tay lên vói trời cao.',explanation:'Biến cố Ba-ben giáng họa sự hỗn độn vỡ mảng đập tan âm mưu tự phụ thống trị của loài người, hậu quả của tội tự suy tôn mình quên đi Vị Hóa Công tột đỉnh.'},
    {answer:'LAMEC',clue:'Hậu duệ hống hách hung tợn của Ca-in khoác lác một bài ca bạo lực sừng sỏ tàn độc khát máu, thề ngập mặt trả thù gấp bảy mươi bảy lần.',explanation:'Bài ca đẫm máu của La-méc chứng minh vũng bùn tội ác thoái hóa tăng vọt lũy tiến của loài người nguyên thủy sau khi tổ tông giáp mặt vườn địa đàng rụng cấm.'},
    {answer:'HENOC',clue:'Bậc tiền bối sống dính chặt gắn bó mật thiết với Thiên Chúa đến mức được rước bổng cất đi bay tít lên trời mà không thèm nếm vị ngám cái chết.',explanation:'Sách Sáng Thế phác họa Hê-nóc đi dạo rảo bước sát cánh với Chúa. Cuộc đời siêu rỗi của ngài dọn sẵn hình bóng những tâm hồn thánh thiện được đem về nhan thánh.'},
    {answer:'MATHUXALA',clue:'Tổ phụ sống thọ chai đá cứng ngắc nhất Kinh Thánh với tuổi đời ngót nghét chín trăm sáu mươi chín năm dằng dặc trước trận đại hồng thủy.',explanation:'Những con số khổng lồ miên man ghi chép tuổi thọ vón vọt thời Cửu Ước bày tỏ sự ban cho trường tồn tưng bừng của Chúa trước khi tội lỗi nhúng chàm tàn phá mòn.'},
    {answer:'SODOM',clue:'Tòa thành trác táng chìm ngập nhớp nháp tội ác kinh khủng bị vùi dập chôn sống bằng những trận mưa sinh diêm cháy rừng rực thiêu đổ rạp.',explanation:'Thiên Chúa không dung tha tội khước từ lệch dâm chướng tai gai mắt nẩy lửa của Sô-đôm. Dù Áp-ra-ham lèo lái mặc cả xin tha tận gốc nhưng không bói ra nổi mười người lanh lẹ công chính.'},
    {answer:'MENKIXEDE',clue:'Vị vua linh mục bí ẩn thành Sa-lem xuất hiện lẫm liệt không nguồn gốc bưng chiếc bánh mỳ với bầu rượu nho dâng tiến và úp tay chúc lành.',explanation:'Không cha không mẹ không gia phả, tư tế vương tước Tối Cao Men-ki-xê-đê xuất thần như chiếc bóng tiền trạm sắc nét đóng rập ấn tín của vị Thượng Tế Giê-su mai sau.'},
  ]},
  {id:59,theme:'Các Thư Thánh Phaolô',words:[
    {answer:'ROMA',clue:'Bức thư vĩ đại đồ sộ nhẫy nhụa nhất trình bày giáo thuyết thần học sắc sống về ơn cứu độ nẩy lộc qua đức tin vô tì vết tuân phục.',explanation:'Tâm điểm thư Rô-ma dập tắt mọi tự kiêu hợm hĩnh vào công lao lề luật chết cứng, mạnh miệng đanh thép xác tín mọi người được xoa chịu nên công chính miễn phí.'},
    {answer:'CORINTO',clue:'Cộng đoàn Hy lạp phức tạp rắc rối được ngài gởi thư khuyên nhủ rát cổ chỉnh đốn tình dục nhố nhăng, phe đảng chia rẽ và ngất ngây diễn tả bài ca Đức ái.',explanation:'Thư thứ nhất củng cố trật tự rập khuôn tiệc Thánh Thể, đặc sủng Thánh Thần tuôn xuống; thư thứ hai đầy lời tự biện hộ xót xa nức nở cõi lòng tông đồ chà đạp.'},
    {answer:'GALATA',clue:'Bức thư phẫn nộ sắc sảo mắng bột nhiếc móc những kẻ hẹp hòi bắt chẹt người dân ngoại nhập đạo phải gò ép cắt bì lóc chóc tuân lề luật nhồi sọ.',explanation:'Thư Ga-la-ta tháo cũi sổ lồng giải phóng tự do bay nhảy vinh quang của con cái Đức Chúa, quật sập hệ thống bó buộc lụi tàn bóng tối do Môi-sê quản thúc nhào nặn.'},
    {answer:'EPHEXO',clue:'Văn thư ngục thất sờn sũi rêu phong viết về mầu nhiệm Giáo Hội tinh tuyền là thân mình nhịp nhàng mà Chúa Kitô là cái Đầu lẫm liệt bất khuất.',explanation:'Cộng đoàn Ê-phê-xô nhận được lời huấn dụ rành rọt đeo trọn vẹn bộ chiến giáp võ phục lẫy lừng của Thiên Chúa để bẻ gãy mọi mũi tên bốc hỏa của xảo quyệt tà ma.'},
    {answer:'PHILIPHE',clue:'Lá thư dạt dào chan chứa tình bác ái tột bậc cùng niềm vui trào dâng hớn hở tuôn ra ồm ộp xối xả lấp liếm giữa chốn ngục tù khét lẹt xiềng xích.',explanation:'Dù gồng mình bị vây bọc lao tù Rô-ma cùm gông vướng víu, vị thánh vẫn tung hô khích lệ cộng đoàn Phi-líp mỉm cười gạt sầu, nức tiếng ca tụng Chúa Kitô vứt bỏ vinh uy.'},
    {answer:'HEBORO',clue:'Bức thư tuyệt cú xoáy sâu chứng minh Chúa Giê-su là vị Thượng Tế độc nhất dâng mình làm của lễ vĩnh viễn bãi bỏ giập tắt các tế tự đẫm máu thú vật.',explanation:'Sách Hê-bơ-rơ liên đới xâu chuỗi Cựu Ước như khúc rễ héo, còn hy tế vớt vát trọn đời một lần của Đấng ngự bên hữu uy linh là sự thành toàn xòa nhòa bóng tối.'},
  ]},
  {id:60,theme:'Hội Thánh Sơ Khai',words:[
    {answer:'HIENXUONG',clue:'Sự kiện gió cuồng phong rung chuyển căn gác xé toạc mái vòm thổi bùng những lưỡi lửa rót Thánh Thần xuống rửa mắt mười một Tông Đồ tịt ngòi.',explanation:'Ngày lễ rực lửa đánh dấu sinh nhật òa khóc vỗ tay chào đời của Giáo hội, phá băng mọi e dè nhút nhát lẩn trốn để vọt miệng lí lo tung hô Thiên Chúa đa ngữ.'},
    {answer:'PHERO',clue:'Vị tông đồ trưởng xuất não bật dậy dõng dạc dảng thuyết thu phục ba ngàn người Rửa Tội róc rách trong đoạn ngày đầu Giáo Hội vươn vai nhấc mình.',explanation:'Từ kẻ chối lia lịa tay lưới bùn hôi thối, Thánh Phê-rô lột xác lãnh trách nhiệm cầm chìa khóa chăn chiên chóp bầy, dám trơ mặt khước từ lời đe dọa chúa tể tử hình.'},
    {answer:'TEPHANO',clue:'Vị tử đạo anh tráng đầu tiên hớn hở ngước lên thấy báu tòa ngỏ cửa liền hứng chịu bão mưa đá tuôn rơi rách thịt gãy xương không oán thù.',explanation:'Mang chức sắc phó tế, thánh Tê-pha-nô cự tuyệt bỏ đạo, sao chép đức tha thứ của Ngài nài nỉ xin đừng tính sổ đổ vấy oán hận tội ác lên đám đông man rợ diệt mình.'},
    {answer:'ANTIOKHIA',clue:'Nôi khởi nguồn rôm rả phồn thực, nơi những tín hữu chập chững thuở ban đầu lần đầu tiên được gắn tên phù hiệu xưng danh vinh dự là Ki-tô hữu.',explanation:'Thành phố An-ti-ô-khi-a khét tiếng sầm uất đóng đô tạo bàn đạp mũi nhọn tung xuất xuất phát điểm dọn đường cho các chiến dịch tông du viễn chinh truyền tin muôn nẻo.'},
    {answer:'CONGVU',clue:'Pho sử thi dạt dào kể lể sinh động oai hùng từng bước đi quật cường vượt biên giới mở rộng đẫm lệ của những người chài lưới vác tin Chúa.',explanation:'Tác phẩm thứ nhì lót thềm của thánh Lu-ca vẽ ra bức tranh nảy mầm vọt lớn mồ hôi tràn trề của Hội Thánh từ chóp đỉnh Giê-ru-sa-lem lan tỏa phăng phăng ra thủ phủ Rô-ma.'},
    {answer:'PHAOLO',clue:'Kẻ bắt đạo hung thú ngã ngựa mù lòa sau đó biến sắc kinh ngạc trở thành lữ khách vĩ đại giong buồm đi lập đoàn dân xứ ngoại biên hoang vu dị giáo.',explanation:'Saolô chuyển hoán quay đầu dõng rạc đổi tên Phao-lô rạc xương gầy mòn trải qua ba ngàn trùng thập tử nhất sinh, rát họng đi gieo vãi để trổ thành vị Tông đồ dân ngoại khổng lồ.'},
  ]},
  { id: 121, theme: 'XH 20: Mười Điều Răn (2)', words: [
    { answer: 'CHA', clue: 'Bậc sinh thành nam giới cốt nhục mà lề luật buộc con cái phải kính trọng vâng lời tận tụy nết na suốt đời.', explanation: 'Điều răn thứ tư là điều răn duy nhất có đính kèm lời hứa ban phúc: "Để tuổi thọ ngươi được kéo dài trên đất Chúa ban".' },
    { answer: 'ME', clue: 'Người phụ nữ cưu mang chín tháng mười ngày, đồng vinh dự bình đẳng với người cha trong điều răn thảo kính đạo đức.', explanation: 'Tôn trọng cha mẹ là tôn trọng chính Thiên Chúa, Đấng đã mượn bàn tay và vòng tay cha mẹ để thông ban hồng ân sự sống.' },
    { answer: 'GIET', clue: 'Hành động cấm kỵ đoạt mạng sống người khác cách bất công tàn bạo, vi phạm nghiêm trọng giới răn thứ năm thiêng liêng.', explanation: 'Chỉ mình Thiên Chúa là chủ thể tuyệt đối của sự sống tử sinh. Cướp đi sinh mệnh tha nhân là tước đoạt quyền tối cao tự quyết của Ngài.' },
    { answer: 'NGOAITINH', clue: 'Sự phản bội ô uế lời thề chung thủy hôn nhân, vi phạm giới răn thứ sáu nhằm bảo vệ tính toàn vẹn sự thánh khiết.', explanation: 'Cấm ngoại tình là bảo vệ gia đình, nơi chốn đầu tiên ươm mầm ơn cứu độ, khỏi sự phá hủy ghê tởm của tính ích kỷ và nhục dục.' },
    { answer: 'TROMCAP', clue: 'Hành vi lén lút hay công khai chiếm đoạt tài sản vốn dĩ thuộc về người khác, được đề cập ở điều răn thứ bảy.', explanation: 'Cấm trộm cắp là nền tảng của công bằng xã hội, bảo vệ quyền sở hữu tư nhân hợp pháp và chống lại lòng xảo quyệt tham lam.' },
    { answer: 'CHUNGDOC', clue: 'Hành vi thề gian dối làm hại người thân cận vô tội trước tòa án hay cộng đồng, vi phạm điều răn thứ tám răn cấm.', explanation: 'Nói dối, vu khống làm rạn nứt niềm tin cộng đồng. Thiên Chúa là Sự Thật, yêu mến Ngài đòi hỏi một đời sống thành thực minh bạch.' }
  ]},
  { id: 122, theme: 'XH 21: Luật Về Quyền Lợi', words: [
    { answer: 'NOLE', clue: 'Tầng lớp lao dịch dưới đáy mà luật quy định chỉ được phép phục vụ tối đa sáu năm, năm thứ bảy phải phóng thích vô điều kiện.', explanation: 'Dù dung túng cho chế độ nô lệ đương thời, luật Môsê mang tính đột phá nhân đạo chưa từng có khi giới hạn thời gian hầu hạ và bảo vệ thân thể họ.' },
    { answer: 'PHONGTHICH', clue: 'Hành động trao trả tự do cho người đang làm kiếp nô bộc nam giới Híp-ri khi họ đã hoàn mãn giới hạn hầu hạ phục vụ.', explanation: 'Sự phóng thích năm thứ bảy gợi nhắc rằng toàn bộ người dân Híp-ri đã từng được Thiên Chúa tự mình phóng thích khỏi ngục tù Ai Cập.' },
    { answer: 'XUXO', clue: 'Hình thức bạo lực tàn phá làm người phụ nữ có thai sẩy thai, sẽ bị trừng hạt trả đũa bằng mạng đền mạng nếu gây tử vong.', explanation: 'Vụ việc sẩy thai phản ánh quan điểm cứng rắn bảo vệ mầm sống trong bụng mẹ, không coi khinh bào thai là một khối máu thịt vô tri vô giác.' },
    { answer: 'DATRAN', clue: 'Vật thể lù lù rơi trúng đầu làm người nào đó chết bất thình lình, nhưng luật sẽ miễn tội cho người chủ đứng trên gác xép lỡ tay.', explanation: 'Sự phân biệt rõ ràng giữa ngộ sát vô ý và cố ý giết người cho thấy một hệ thống luật pháp sâu sắc chú trọng vào động cơ hành vi.' },
    { answer: 'MAT', clue: 'Bộ phận thị giác mà nếu kẻ nào cố tình chọc đui của người khác thì bắt buộc phải bị móc đền bù lại giống y như sự thể.', explanation: 'Luật "Mắt đền mắt" (Lex Talionis) thoạt nghe có vẻ dã man, nhưng lại là sự tiến bộ nhằm kiểm soát mức độ trả thù bừa bãi không giới hạn.' },
    { answer: 'RANG', clue: 'Bộ phận nhai cắn trên mặt bị gãy do bạo lực, người chủ khiến nô lệ gãy mất thứ này phải trả giá bằng việc thả tự do cho nô lệ đi.', explanation: 'Thả tự do đền bù chiếc răng gãy là cách thiết thực bảo vệ kẻ yếu thế thảm hại khỏi sự lạm dụng tàn nhẫn của quyền lực làm chủ.' }
  ]}
];
