module.exports = [
  {id:46,theme:'Chúa Giêsu Chữa Lành',words:[
    {answer:'PHONGHUI',clue:'Căn bệnh ngoài da tước đoạt nhân phẩm người mắc phải, nhưng đã biến mất khi Chúa chạnh lòng chạm tay vào.',explanation:'Bệnh phong trong xã hội Do Thái cổ bị coi là ô uế. Chúa Giêsu vượt qua lề luật để chạm vào họ, trả lại phẩm giá con người.'},
    {answer:'BATIME',clue:'Anh mù mù lòa dạn dĩ kiên trì ngồi bên vệ đường Giêricô, van nài xin Con vua Đavít thương xót.',explanation:'Người mù Báctimê đại diện cho đức tin. Bất chấp đám đông mắng bảo im, anh vất áo choàng cản đường chạy đến xin Chúa chữa lành.'},
    {answer:'LADARO',clue:'Người bạn quý mến của Chúa ở Bêtania, tuy đã nằm liệt trong mồ bốn ngày nhưng vẫn bước ra khi được gọi.',explanation:'Phép lạ phục sinh Ladarô là đỉnh cao quyền năng của Chúa trên sự chết, đồng thời là dấu chỉ báo trước sự kiện Ngài Phục Sinh.'},
    {answer:'DAKEU',clue:'Người trưởng ấn thu thuế nhỏ bé trèo lên cây sung để ngắm nhìn Chúa ngang qua, cuối cùng vinh dự rước Chúa vào nhà.',explanation:'Sự kiện Giakêu ở Giêricô minh chứng sức mạnh ơn hoán cải. Ánh nhìn bao dung của Chúa khiến ông hối lỗi hứa đem chia nửa tài sản.'},
    {answer:'DOITRUONG',clue:'Viên sĩ quan La Mã có đức tin khiêm cung vĩ đại, xin Chúa chỉ phán một lời từ xa thì đầy tớ ông sẽ khỏi bệnh.',explanation:'Lời tuyên xưng khiêm nhường thiết tha của viên bách quản đã trở thành lời kinh được Hội Thánh xướng lên hằng ngày trước lúc rước lễ.'},
    {answer:'HUYETLAU',clue:'Căn bệnh rong máu đeo bám người phụ nữ ròng rã mười hai năm, nhưng bà chỉ cần chạm nhẹ áo Chúa đã được chữa lành.',explanation:'Người đàn bà mắc bệnh loạn huyết lén lút rờ tay vào gấu áo Chúa là minh chứng sống động của một đức tin âm thầm nhưng phi thường vững mạnh.'},
  ]},
  {id:47,theme:'Tâm Tình Phúc Âm',words:[
    {answer:'KHIEMNHUONG',clue:'Đức tính thẳm sâu nhận biết thân phận mình mỏng manh, coi người khác trọng hơn chính bản thân như tấm gương từ Chúa.',explanation:'Thiên Chúa dạy rằng ai tự cất mình lên sẽ bị hạ xuống, ai khiêm hạ tự hạ mình xuống hèn mọn sẽ được suy tôn vinh diệu trong Nước Trời.'},
    {answer:'HIENLANH',clue:'Sức mạnh tịnh tâm êm dịu không dùng bạo lực trả đũa đối phương, vì chính họ sẽ được vùng Đất Hứa làm gia nghiệp.',explanation:'Sự hiền lành Phúc Âm không phải nhu nhược yếu kém mà là năng lực lớn lao chế ngự được vòng xoáy hận thù, thuận theo gương kiên nhẫn Chúa Giêsu.'},
    {answer:'PHUCVU',clue:'Tiêu chí cao nhất của chức vụ quyền bính trong Đạo: ai muốn làm bề trên thì phải biết cúi xuống hầu hạ mọi người anh em.',explanation:'Trái ngược với thói đời xưng vương xưng tướng đòi mọi người suy phục hầu hạ, đường lối Kitô Giáo là người nắm quyền phải phục vụ đàn chiên.'},
    {answer:'HYSINH',clue:'Sự quảng đại từ bỏ thầm lặng vì người khác, tựa như hạt lúa mì bằng lòng mục nát chết đi vì rụng xuống để sinh nhiều bông hạt.',explanation:'Bước theo dấu chân thập giá Cứu Độ, mọi điều tốt lành trong đời sống đều cần nảy nở sinh chồi từ một tình yêu hy sinh bác ái hiến thân mình vì anh em.'},
    {answer:'NGHEOKHO',clue:'Mối phúc dẫn đầu và là nền móng cửa ngõ Nước Trời, mời gọi tâm hồn không dính bén bám víu vào chốn bộn bề vàng ngọc.',explanation:'Tinh thần nghèo khó là tự do không lệ thuộc vào vật chất trần thế, dạt hết tư lợi mà đặt trọn niềm hi vọng phần an bình đời mình vào Thiên Chúa.'},
    {answer:'NHANNHUC',clue:'Sức chịu đựng gian khổ nhẫn nại cách phi thường khi bị vu ăn bách hại oan ức vì niềm tin mà không buông lời thóa mạ căm hờn nguyền rủa.',explanation:'Cử chỉ sẵn lòng chìa má kia cho kẻ tát mình gò phải là một hình ảnh khải thị sống động của cách sống nhẫn nhục nhường hi sinh tha thứ bao dung cao thượng trong cốt lõi tinh túy của đạo.'},
  ]},
  {id:48,theme:'Bí Tích Thánh Thể',words:[
    {answer:'TIECLY',clue:'Bữa ăn tối trước cuộc Khổ Nạn, nơi Bí Tích Thánh Thể được chính thức thiết lập.',explanation:'Bữa Tiệc Ly thiết lập giao ước mới bọc trong Máu ban cho Giáo Hội, cùng với lệnh truyền: "Hãy làm việc này mà nhớ đến Thầy".'},
    {answer:'TRUYENPHEP',clue:'Trọng tâm của kinh Tạ Ơn, khi linh mục lặp lại lời của Chúa Giêsu lúc Người dâng bánh miến và rượu nho.',explanation:'Thông qua lời truyền phép và quyền năng Chúa Thánh Thần, bản thể tiến lễ bánh rượu thực sự trở thành Mình Máu Thánh Chúa.'},
    {answer:'BIENTHE',clue:'Mầu nhiệm thiêng liêng khi bản thể bánh rượu chuyển hóa hoàn toàn thành chính Mình Máu Thánh Chúa Kitô.',explanation:'Thuyết Biến Thể (Transubstantiation) khẳng định: Dù hình thức bên ngoài vẫn là bánh rượu, nhưng bản thể thâm sâu đã trở thành chính Đức Kitô toàn tại.'},
    {answer:'RUOCLE',clue:'Hành động thiêng liêng rước Mình và Máu Thánh Chúa vào lòng để hiệp thông trọn vẹn với Ngài.',explanation:'Rước lễ là tột đỉnh của sự hiệp thông Kitô giáo, mang lấy chính hạt giống phục sinh vào thân xác để nuôi dưỡng mầm sống đời đời.'},
    {answer:'NHATAM',clue:'Nơi lưu giữ cách an toàn và tôn nghiêm Mình Thánh Chúa đặt ở gian cung thánh nhà thờ.',explanation:'Nhà Tạm với ngọn đèn chầu đỏ luôn thắp sáng nhắc nhở Chúa vẫn hằng hiện diện thực sự ở đó để đón đợi giáo dân viếng thăm.'},
    {answer:'MATNHAT',clue:'Hộp lồng rực rỡ để tỏ bày Mình Thánh Chúa cho cộng đoàn dân Chúa chiêm ngắm và tôn thờ.',explanation:'Mặt Nhật phô bày Mình Thánh Chúa để giáo dân chầu nhan Thánh Thể, chiêm ngắm Tình Yêu Nhập Thể đang hiện diện trọn vẹn.'},
  ]},
  {id:49,theme:'Sứ Mạng Truyền Giáo',words:[
    {answer:'TRUYENGIAO',clue:'Mệnh lệnh khẩn thiết của Giáo Hội: đem niềm vui Phúc Âm loan báo đến mọi nơi trên toàn thế giới.',explanation:'Truyền giáo không phải là sự áp đặt, mà là sức cuốn hút của một cộng đoàn bác ái, sẵn sàng dấn thân ra những vùng ngoại biên.'},
    {answer:'TINMUNG',clue:'Thông điệp rạng rỡ của ơn cứu độ, Tin Vui mà các tông đồ hăng hái mang đi rao giảng tứ phương.',explanation:'Tin Mừng không phải là một bộ luật gò bó, mà là sự xác quyết sưởi ấm tâm hồn rằng Thiên Chúa đã nhập thể sống cùng loài người.'},
    {answer:'TUDAO',clue:'Hành vi làm chứng cao cả nhất cho đức tin khi sẵn sàng đổ máu đào tử đạo thay vì chối bỏ Chúa.',explanation:'Máu các vị tử đạo là hạt giống nảy sinh các Kitô hữu. Sự hy sinh đến cùng vì danh Chúa là phép rửa rạng ngời lòng trung kiên.'},
    {answer:'DUTONG',clue:'Những người đang tìm hiểu và khao khát đức tin, được chuẩn bị từng bước trước khi lãnh Bí Tích Thanh Tẩy.',explanation:'Thời kỳ dự tòng là hành trình hoán cải tâm hồn, từ bỏ nếp sống lầm lạc cũ để chuẩn bị đắm mình vào Rửa Tội vinh phúc.'},
    {answer:'RUATOI',clue:'Bí tích tẩy sạch tội tổ tông, chính thức tháp nhập người tín hữu vào Nhiệm Thể Giáo Hội.',explanation:'Bí Tích Rửa Tội là cánh cửa của các bí tích, ban cho con người địa vị làm con Chúa và tham dự vào ba chức vụ: tư tế, vương giả, tiên tri.'},
    {answer:'TONGDO',clue:'Nhóm mười hai vị nòng cốt được Chúa đích thân tuyển chọn và cắt cử sai đi rao giảng Nước Trời.',explanation:'Kế vị các tông đồ, mọi Kitô hữu đều có ơn gọi và sứ vụ làm chứng nhân, gieo mầm Phúc Âm giữa lòng thế giới rộng lớn.'},
  ]},
  {id:50,theme:'Biểu Tượng Kinh Thánh',words:[
    {answer:'CAYNHO',clue:'Hình ảnh Chúa Giêsu là Thân Nho, còn chúng ta là những cành nho tiếp nối liền chặt để sinh hoa trái.',explanation:'Chúa dạy cành nho không thể tự mình sinh trái, nếu tự kiêu tách rời khỏi gốc Nho là tình yêu Chúa thì sẽ héo khô cằn cỗi.'},
    {answer:'MUCTU',clue:'Vị mục đồng nhân lành sẵn sàng để lại chín mươi chín con chiên để đi tìm cho kỳ được con chiên lạc lối.',explanation:'Chúa Kitô là hình mẫu tột bậc của Vị Mục Tử nhân lành, Ngài yêu thương nhẫn nại và không ngớt sẵn sàng hy sinh mạng sống vì đoàn chiên.'},
    {answer:'MANNA',clue:'Thứ bánh kỳ diệu từ trời rơi xuống như sương mỗi sáng tinh mơ để nuôi dân Chúa trong hoang địa.',explanation:'Bánh Manna là hình ảnh tiên báo Thánh Thể, thứ Bánh Hằng Sống ban sự sống đời đời dư tràn cho nhân trần lữ hành.'},
    {answer:'BOCAU',clue:'Hình ảnh loài chim trắng hiền hòa thường được dùng để diễn tả sự ngự xuống của Chúa Thánh Thần.',explanation:'Bồ câu xuất hiện tại dòng sông Giođan tượng trưng cho Chúa Thánh Thần ngự xuống, xác nhận vương quyền và thân phận của Chúa Con yêu dấu.'},
    {answer:'CHIENCON',clue:'Biểu tượng con vật chịu sát tế trong lễ Vượt Qua cũ ám chỉ sự tự hiến của Đấng Cứu Độ.',explanation:'Giống như chiên Vượt Qua xưa cứu dân khỏi tử thần, máu Chiên Mới là Đức Kitô đã đổ ra đem lại ơn tha tội và sự sống mới.'},
    {answer:'MAOGAI',clue:'Chiếc vòng gai sắc nhọn nhuốm máu đội trên đầu Chúa Giêsu, sau vụt sáng thành chiếc vương miện khải hoàn.',explanation:'Từ công cụ đớn đau hèn hạ để nhạo báng, mão gai nhuốm máu cứu chuộc đã hóa thân thành vương miện vinh quang hiển linh tuyệt trần.'},
  ]},
  { id: 117, theme: 'XH 17: Nước Từ Tảng Đá', words: [
    { answer: 'TANGDA', clue: 'Khối đá cứng ở núi Horep tuôn trào dòng nước mát lạnh khi bị chiếc gậy của Môsê đập vào.', explanation: 'Tảng đá bị đập vỡ là hình ảnh báo trước Đức Kitô bị đâm thâu để ban Mạch Nước Hằng Sống cho nhân loại nương nhờ.' },
    { answer: 'GAY', clue: 'Chiếc gậy Môsê từng dùng để rẽ Biển Đỏ, nay lại được lệnh vung dùng đập vào phiến đá.', explanation: 'Chiếc gậy không có năng lực tự thân, nó chỉ mang sức mạnh khi được vâng lời Thiên Chúa để thực thi quyền phép.' },
    { answer: 'NUOC', clue: 'Mạch suối trào ra từ vách đá giúp toàn bầy dân chúng và súc vật được giải cơn khát cồn cào giữa sa mạc.', explanation: 'Dòng nước tuôn đổ nơi hoang mạc là biểu tượng hồng ân sự sống nhưng không, xoa dịu cơn giận dữ oán trách tột độ của Israel.' },
    { answer: 'MASA', clue: 'Tên gọi có nghĩa là "thử thách", đặt cho địa danh vì dân Chúa đã nhẫn tâm kêu ca và thử thách Ngài.', explanation: 'Massa và Meriva trở thành sự kiện buồn bã tượng trưng cho sự cứng lòng của dân Chúa trước những hồng ân giải thoát hiển nhiên.' },
    { answer: 'OANTRACH', clue: 'Thái độ bực tức của dân Israel khi thiếu nước, vội hồ nghi chất vấn xem liệu Đức Chúa có đang ở cùng họ.', explanation: 'Sự oán trách không chỉ phàn nàn về thể xác mà còn là sự xói mòn niềm tin, phủ nhận sự đồng hành của Chúa che chở.' },
    { answer: 'BATMAN', clue: 'Cảm giác chán nản của Môsê khi phải đối diện với sự hung bạo đòi ném đá tử hình từ đám đông khát nước.', explanation: 'Sự bất mãn phẫn uất của dân chúng đẩy Môsê đến nỗi kêu cứu cùng Chúa: "Họ sắp ném đá con đến nơi rồi!"' }
  ]},
  { id: 118, theme: 'XH 18: Gít-rô Khuyên Nhủ', words: [
    { answer: 'GITRO', clue: 'Tư tế xứ Mađian và là cha vợ khôn ngoan của Môsê, người đã dắt con gái và hai cháu ngoại đến viếng thăm.', explanation: 'Sự xuất hiện của Gítrô đánh dấu vị một Tư Tế dòng ngoại giáo nhận biết những kỳ công Chúa làm cho Israel.' },
    { answer: 'VIPHAM', clue: 'Các tranh chấp lầm lỗi mà dân chúng kéo nhau đến chầu chực từ sáng tới chiều nhờ vị lãnh tụ phân xử.', explanation: 'Tình trạng kéo đến quá tải phản ánh sự bất tiện và thiếu tổ chức cộng đồng trong bộn bề lề luật.' },
    { answer: 'XETXU', clue: 'Công việc phân định đúng sai căng thẳng mà Môsê đã ôm đồm một mình từ ban sớm đến khi đêm đen.', explanation: 'Việc Môsê một mình phân xử phô bày sự tận tụy lớn lao, nhưng bộc lộ rủi ro kiệt quệ sinh lực do bất cập người phụ giúp.' },
    { answer: 'LOIKHUYEN', clue: 'Giải pháp quản lý khôn ngoan mà vị cha vợ đưa ra: nên chia sẻ gánh nặng xử án với các cộng sự tài đức.', explanation: 'Lời khuyên của Gítrô là nền tảng quý giá về tầm nhìn thiết chế: biết phân quyền bính lãnh đạo để giảm tải căng thẳng cá nhân.' },
    { answer: 'CHIETEU', clue: 'Sự phân cấp dân chúng thành các nhóm ngàn người đội phó ngót lại thành trăm và chục để dễ bảo ban.', explanation: 'Chia các tiểu đội nhằm mục đích thiết lập hệ thống cố vấn tư pháp sơ khởi hiệu quả đầu tiên trong dân.' },
    { answer: 'KHOELUYEN', clue: 'Tiêu chuẩn chọn người phân xử: tìm những người tài năng nhân đức, kính sợ Thiên Chúa và ghét hối lộ.', explanation: 'Một pháp chế vững trị cần rường cột con người không chỉ có khả năng quyết đáp mà còn cần liêm minh chính trực không mưu tư lợi.' }
  ]}
];
