module.exports = [
  {id:26,theme:'Vua Đavít',words:[
    {answer:'DAVIT',clue:'Vị vua xuất thân là cậu bé chăn chiên, người đã gảy đàn hạc và sáng tác vô số Thánh Vịnh ca tụng Thiên Chúa.',explanation:'Đavít là vị vua vĩ đại nhất của Israel. Dù có những lúc yếu đuối phạm tội, ông luôn biết thật lòng thống hối ăn năn xin Chúa thứ tha.'},
    {answer:'GOLIAT',clue:'Tên lính khổng lồ kiêu ngạo thách thức đạo binh Israel, nhưng đã bị đánh bại bởi một viên sỏi chăn chiên nhỏ bé.',explanation:'Trận chiến giữa Đavít và Gôliát là minh chứng quyền năng Thiên Chúa: Ngài không cần gươm giáo khổng lồ để đánh bại sự kiêu căng của thế gian.'},
    {answer:'SALOMON',clue:'Vị vua bề thế là con trai của Đavít, lừng danh thiên hạ vì sự khôn ngoan và công trình xây cất Đền Thờ Giêrusalem.',explanation:'Dù có khởi đầu rực rỡ, vua Salômon cuối đời lại sa ngã vì đã chiều chuộng các bà vợ ngoại giáo mà quay sang thờ lạy các thần tượng.'},
    {answer:'NATAN',clue:'Vị ngôn sứ dám can đảm mượn dụ ngôn con chiên nhỏ để thẳng thắn vạch trần tội ác của nhà vua Đavít.',explanation:'Lời chất vấn "Kẻ đó chính là ngài!" của Natan như nhát gươm đâm thấu khiến Đavít thức tỉnh và thốt lên: "Tôi đã đắc tội với Đức Chúa".'},
    {answer:'SAUN',clue:'Vị vua đầu tiên của dân Israel có vóc dáng cao to nhưng sau này bị Thiên Chúa phế truất vì đã bất tuân lời Ngài.',explanation:'Saun ban đầu được xức dầu tuyển chọn, nhưng sau do ghen tị với tài năng của Đavít mà tự chuốc lấy thảm kịch diệt vong mất ngôi báu.'},
    {answer:'GIESE',clue:'Người cha cư ngụ vùng Bêlem có tất cả tám người con trai. Từ gốc tích nhà này, một mầm non là Đấng Cứu Thế đã xuất hiện.',explanation:'"Từ gốc Giêsê, một mầm non sẽ vươn lên". Lời tiên tri Isaia báo trước Chúa Giêsu sẽ xuất thân từ hoàng tộc Đavít, con trai thứ tám của Giêsê.'},
  ]},
  {id:27,theme:'Hành Trình Phaolô',words:[
    {answer:'PHAOLO',clue:'Vị tông đồ xuất chúng của Dân Ngoại, vượt qua biến cố mù lòa trên đường Đamát để trở thành nhà rao giảng đầy nhiệt huyết.',explanation:'Phaolô không thuộc Nhóm Mười Hai, nhưng với kiến thức uyên bác và lòng cậy mến, ngài đã đem Tin Mừng vượt khỏi ranh giới xứ Do Thái.'},
    {answer:'DAMAT',clue:'Thành phố mang dấu ấn biến cuộc đời Phaolô khi ngài đang trên đường đi tróc nã thì bị ánh sáng từ trời đánh gục mù lòa.',explanation:'Biến cố trên đường đi Đamát là bước ngoặt kỳ vĩ nhất của Giáo Hội sơ khai, biến một kẻ lùng sục đạo thành vị tông đồ tận tâm nhất.'},
    {answer:'BANABA',clue:'Nhân vật mang biệt danh "con của sự an ủi", đã dũng cảm bảo lãnh cho một Phaolô đang bị ngờ vực trước Giáo Hội sơ khai.',explanation:'Ông Banaba đã quảng đại bán đất đem tiền nộp Hội Thánh, và cũng là người dìu dắt Phaolô trong chặng đường truyền giáo gian nan những rảo chân đầu.'},
    {answer:'TITO',clue:'Người cộng sự thân tín được thánh Phaolô viết hẳn một bức thư mục vụ tận tình để hướng dẫn cách điều hành cộng đoàn Hội thánh.',explanation:'Thánh Titô được cắt cử phụ trách cộng đoàn tại đảo Kêta. Bức thư gửi ngài chứa đựng những huấn thị cực kỳ thực tế về bổn phận mục tử chăn dắt.'},
    {answer:'CORINTO',clue:'Thành phố cảng sầm uất, nơi thánh Phaolô từng rao giảng và sau đó viết cho cộng đoàn ở đó bài ca tuyệt diệu về Đức Mến.',explanation:'Tại Côrintô, Phaolô vừa phải tự dệt lều kiếm sống vừa rao giảng. Bức thư ngài gửi cho họ chứa đựng thi ca ngợi ca về tình yêu không phai mờ.'},
    {answer:'ROMA',clue:'Điểm đến oai hùng cuối cùng trong chặng đường lưu đày truyền giáo của thánh Phaolô, nơi ngài bị trảm quyết tử đạo làm chứng nhân.',explanation:'Roma là trái tim vĩ đại đế quốc La Mã. Tại đây, Phaolô và Phêrô đã đổ máu tử đạo gieo hạt giống đức tin kiên cường cho toàn mảnh đất Âu Châu.'},
  ]},
  {id:28,theme:'Công Vụ Tông Đồ',words:[
    {answer:'LUCA',clue:'Tác giả của cuốn sách lịch sử thiêng liêng ghi chép lại chặng đường truyền giáo đầu tiên và sự phát triển của Hội Thánh sơ khai.',explanation:'Sách Công Vụ Tông Đồ do Thánh Luca chép lại tựa như bảo tàng tư liệu vô giá về lộ trình đi gieo hạt giống Tin Mừng đầy gian truân thời ban đầu.'},
    {answer:'PHERO',clue:'Vị Tông Đồ Trưởng đã vững mạnh đứng lên thuyết giảng cách dõng dạc trong ngày Lễ Ngũ Tuần thu phục hàng ngàn tân tòng.',explanation:'Nhờ ơn Thánh Thần biến đổi, từ một Phêrô từng mang nét yếu hèn khước Chúa, ngài đã can trường mở toang cửa lao ra đường phố truyềno giảng không nề hà nao núng.'},
    {answer:'TEPHano',clue:'Vị phó tế đầu tiên anh dũng ngã xuống vì đạo dưới cơn mưa đá, cõi lòng bao dung vẫn lớn tiếng xin Chúa tha thứ cho những kẻ bức hại mình.',explanation:'Hạt giống tử đạo đẫm nhuộm máu của Têphanô đã trở thành ngọn nguồn ơn thánh thúc đẩy sự cải hóa đổi thay tâm hồn thanh niên Saolô cầm áo gần đó.'},
    {answer:'MATHIA',clue:'Nhân vật được cộng đoàn sơ khai hiệp ý bốc thăm trúng tuyển để lấp bổ khuyết vào cái ghế trống vị trí của kẻ phản Thầy Giuđa Iscariot.',explanation:'Nhằm kiện toàn biểu trưng uy hùng mười hai chi tộc Israel cho Nhóm Mười Hai, công đoàn đã nguyện xin ý Chúa chỉ định ông Mátthia cáng đáng.'},
    {answer:'ANTIOKHIA',clue:'Thung lũng điểm ranh đầu tiên nơi tín hữu theo đường lối của Chúa Giêsu được người đời bắt đầu trực tiếp gọi rành rẽ bằng danh xưng Kitô hữu.',explanation:'Antiôkhia là trung tâm truyền giáo phát điểm chính trong chặng đường của Phaolô, nơi ranh hào ngăn cách phân bì giữa người Do Thái và dân ngoại bị cởi bỏ.'},
    {answer:'PHILIPHE',clue:'Vị phó tế đã mau mắn vâng lệnh Thánh Thần ra đón chiếc xe ngựa để giải nghĩa Kinh Thánh và làm Phép Rửa nước cho viên quan ngự thái giám Êtiôpi.',explanation:'Cuộc đối thoại trên xa lộ minh chứng rõ nét sự can thiệp của Thánh Thần luôn là tác nhân chủ chốt gieo hạt đức tin nơi một trái tim đang tìm kiếm Chúa.'},
  ]},
  {id:29,theme:'Kinh Thánh Lời Chúa',words:[
    {answer:'KINHTHANH',clue:'Bộ sách thiêng liêng vĩ đại gồm bảy mươi ba cuốn, được Thiên Chúa linh hứng cho các tác giả nhân loại tuyển tập chép lại.',explanation:'Kinh Thánh không phải là di thư thần bí vô tri rớt từ trên mây xuống, mà chân thực là Lời Hằng Sống được diễn đạt bằng ngôn ngữ và bối cảnh trần thế của loài người.'},
    {answer:'CUUUOC',clue:'Phần mở đầu gồm bốn mươi sáu cuốn sách mang tính nền tảng kể lại quá trình dọn đường lịch sử và những lời thề hứa Cứu Độ bảo chứng.',explanation:'Ghi chép hành trình Thiên Chúa kiên nhẫn giáo dục dân riêng Israel dần qua lề luật giao điều và ngôn sứ, trải thảm dọn lối chờ đón Mặt Trời Công Chính.'},
    {answer:'TANUOC',clue:'Phần sách cực cốt lõi chắt đúc trong hai mươi bảy cuốn thư từ, tường thuật hành trình làm người và công cuộc tử nạn cứu chuộc của Đức Kitô.',explanation:'Bản tóm lược trọn vẹn diệu kỳ về một Giao Ước Mới được quyết định lập thành bằng dính chính Máu Chúa Giêsu, để khép lại một cách viên mãn toàn bộ tiến trình mặc khải.'},
    {answer:'TINMUNG',clue:'Bốn cuốn Phúc Âm quan trọng truyền tải cách trực tiếp nhất nhịp đập cuộc đời, những giới điều tu sống giáo lý huấn từ và phép lạ của Chúa Giêsu.',explanation:'Mátthêu, Máccô, Luca và Gioan là mốc tư trụ như bốn lăng kính rực rỡ lột tả chân thực chân dung bất diệt của Đấng Cứu Thế cho muôn hằng thế hệ chiêm ngắm.'},
    {answer:'LINHHUNG',clue:'Sự tác động trợ lực thiêng liêng mầu nhiệm của Chúa Thánh Thần nhằm hướng dẫn các tác giả trần sao viết đúng trọn vẹn Lời Chúa mà không thể sai lầm.',explanation:'Thiên Chúa vận dụng các tác giả tựa thể người nhạc công đàn tấu khúc cầm. Tiếng vang đặc tính cá nhân mỗi người vẫn còn rành rật đó, hòa làm một hợp xướng thành ý Thiên Thần.'},
    {answer:'GIAOHUAN',clue:'Thẩm quyền uy thế hướng quy thuộc về hội đồng Hội Thánh nhằm diễn giải các thông điệp giáo lý Lời Chúa cách thức bảo đảm không hề bị sai lệch.',explanation:'Ta không nên và không được tự quyền cắt xén rồi áp dụng giải nghĩa Kinh Thánh theo cái cá tâm. Quyền Huấn Quyền của các đấng bề trên sẽ canh phòng gìn giữ một đức tin chân nguyên thuần dốc.'},
  ]},
  {id:30,theme:'Đời Sống Phụng Vụ',words:[
    {answer:'GIOKINH',clue:'Phụng vụ ngợi khen Thiên Chúa quy định chia khung thời khắc xuyên đêm ngày, đặc biệt nổi bật nhất là vị trí Kinh Sáng buổi hồng đông và Kinh Chiều khi màn buông.',explanation:'Không chỉ là chuyện dành biệt vị cho giới tu sĩ kín cổng cao tường, Phụng vụ Giờ Kinh thực ra là vinh phần hòa chung điệu hỷ hoan dâng lên Chúa giữa khoảnh sống đan xen bận rộn.'},
    {answer:'THANHCA',clue:'Bài hát thánh thi mang rập theo giai điệu chuẩn mực quy định phụng vụ linh thánh, được hợp xướng cất lên để xướng nâng tâm hồn hòa điệu ngưỡng vọng Thiên Chúa.',explanation:'Thánh ca đúng nghĩa nhằm xoay chuyển thăng hoa tâm tình hội thánh chứ không thể hiện sự ca vãn kể khổ mướt mát ủy mị hay phô diễn sở trường ca tông uốn éo cá nhân chủ xướng.'},
    {answer:'DANGLE',clue:'Hành vi trọng đại điểm đỉnh nơi cung thánh linh mục bẻ thiết bánh rượu, nhiệm tích hóa hiển tại lại toàn vẹn tái hiện hiến tế đền mạng của Chúa trên rặng Canvê năm nảo.',explanation:'Bưng khay lễ vật, hàng người tín hữu đồng điệu theo đó mang hòa gom hết vất vả nhọc nhằn lao trần cùng dâng kèm thành khối hiệp tế giao kết cùng trót Chúa Kitô vinh tôn trình nộp lên Chúa Cha an bài.'},
    {answer:'TAMNHAT',clue:'Chuỗi xâu kết rành rành cực điểm ba ngày tuyệt linh thiêng trong chu trình năm phụng vụ, đặc biệt rọi sáng tưởng nhớ lại tận nguồn mầu nhiệm Vượt Qua của Chúa Giêsu rức tàn.',explanation:'Tam Nhật Thánh thật ra không phải là những mảnh lắp ghép đứt rã mà kéo thành nguyên một sợi triệt dài liền lạc cuộc lễ duy nhất. Nhát rạch khởi mốc Tiệc Ly tối Thứ Năm dăng xuyên qua Đêm Lễ lớn Mừng Chúa Sống Lại.'},
    {answer:'KIENGTHIT',clue:'Luật lệ ép thực hiện kìm hãm sở thích áp định độ tuổi giáo hữu từ tròn khóp mười bốn tuổi lớn lên răn giữ bó sát trong ngày chay như đặc thù bữa Thứ Sáu Tuần Thánh.',explanation:'Trừng ý không nằm trong tính khôn chanh ăn mẹo (như ăn cá tôm đồ biển khoái khẩu thế cá), cốt lõi giữ kiêng thực là hy sinh nhường tước đi một thứ đồ ngon món quen hậm hực để kết dính tâm hồn vào sự khốn túng đau chia cái chết đồi sọ của Thầy.'},
    {answer:'ANCHAY',clue:'Việc tự rèn ép bỏ bớt thu hẹp khẩu ăn cốt để mài chuốc đớn hy sinh bản diện bù hiệp thông thanh luyện với chuỗi rã ròng khổ hình khốc liệt mà Chúa chịu trui rèn.',explanation:'Luật chay khắc khe bó buộc (khung mốc từ thập bát tròn đến khép 59 xuân) ở riêng Thứ Tư Lễ Tro và mùa Thứ Sáu đau thương. Thụ chay hạn bao tử để dạ tâm thanh sảng đủ cõi chỗ đón rước ơn linh thánh soi tràn.'},
  ]},
  { id: 109, theme: 'XH 9: Dịch Súc Vật & Mưa Đá', words: [
    { answer: 'ONGDICH', clue: 'Tai ương thứ năm làm chết hàng loạt ngựa, lừa, lạc đà và gia súc của người Ai Cập ngoài đồng.', explanation: 'Dịch bệnh tàn phá nguồn lực nông nghiệp và quân sự của Ai Cập, phơi bày sự mong manh của đế quốc kiêu hãnh.' },
    { answer: 'UNGNHOT', clue: 'Tai ương thứ sáu gây mụn mủ lở loét đau đớn nổi khắp cơ thể dân chúng và súc vật Ai Cập.', explanation: 'Môsê ném tro tung lên trời, tro hóa thành ung nhọt. Tai ương này tấn công trực tiếp vào thân thể mang lại sự đau đớn cùng cực.' },
    { answer: 'MUADA', clue: 'Trận mưa vô tiền khoáng hậu đổ xuống những tảng đá băng kèm sấm sét tàn phá mọi thứ ngoài đồng trống.', explanation: 'Cơn mưa đá khốc liệt giáng xuống càn quét thảm khốc cây cối và súc vật, đánh gục hy vọng vào các thần linh cai quản thời tiết.' },
    { answer: 'CAYCO', clue: 'Hệ thực vật và mùa màng bị trận mưa đá khốc liệt đập nát không thương tiếc.', explanation: 'Mưa đá không chỉ giết người và vật mà còn tàn phá thảm thực vật, giáng đòn chí mạng vào nguồn lương thực của vua Pharaô.' },
    { answer: 'TRO', clue: 'Thứ bụi tàn mà Môsê đem tung lên không trung để sinh ra mầm bệnh ung nhọt ngứa ngáy.', explanation: 'Tro bụi bay trong gió tưởng chừng vô hại, nhưng dưới quyền năng Thiên Chúa lại trở thành mầm mống mụn nhọt ác tính.' },
    { answer: 'NGUA', clue: 'Loài vật quan trọng vốn làm sức kéo cho chiến xa của đế chế Ai Cập đã lăn ra chết vì dịch bệnh.', explanation: 'Sự sụp đổ tiệt giống của lực lượng kỵ mã Ai Cập làm suy yếu sức mạnh quân sự đáng gờm nhất của vương triều Pharaô tàn bạo.' }
  ]},
  { id: 110, theme: 'XH 10: Châu Chấu Và Bóng Tối', words: [
    { answer: 'CHAUCHAU', clue: 'Tai ương thứ tám kinh hoàng với bầy côn trùng bay đến xâu xé ăn sạch mầm cây rễ cành sót lại.', explanation: 'Bầy châu chấu vây đen kịt bầu trời ăn trụi mầm sống cuối cùng, chứng minh thiên nhiên hoàn toàn tùng phục quyền hành của Đức Chúa.' },
    { answer: 'BONGTOI', clue: 'Màn đêm đặc quánh đáng sợ nhấn chìm toàn thể cõi Ai Cập tăm tối bao phủ ròng rã suốt ba ngày.', explanation: 'Bóng tối là tai ương thứ chín, đánh bại thần Mặt Trời Ra tối cao nhất của người Ai Cập, nhấn chìm họ vào sự sợ hãi cực độ.' },
    { answer: 'GOSEN', clue: 'Vùng đệm an toàn nơi dân Chúa sinh sống, ngập tràn ánh sáng dù phần còn lại của Ai Cập chìm trong tối tăm.', explanation: 'Ánh sáng rọi chiếu trên nhà người Israel giữa lúc bóng tối bủa vây là điềm báo Chúa cứu rỗi những kẻ tin thờ Ngài.' },
    { answer: 'SAMHOI', clue: 'Hành động giả tạo của vua Ai Cập khi van xin Môsê tha thứ mỗi chặng tai họa vượt mức chịu đựng.', explanation: 'Sự ăn năn nông cạn chỉ cất lên khi gặp khốn cùng, còn sau lúc tai họa đi qua thì Pharaô lại tiếp tục ngoan cố cứng lòng.' },
    { answer: 'MUHET', clue: 'Trạng thái tối tăm cản trở hoàn toàn tầm nhìn khiến người Ai Cập không ai dám rời khỏi chỗ mình tận ba ngày.', explanation: 'Bóng tối dày đặc dường như có thể cảm rõ được bằng tay, mang đến sự tê liệt hoàn toàn cho đế chế từng một thời tự cao tột đỉnh.' },
    { answer: 'PHA', clue: 'Hành động phá hoại triệt để của đám côn trùng dọn sạch sẽ mầm xanh, cỏ cây hoa lá sót lại mà mưa đá chưa diệt hết.', explanation: 'Sự phá hủy triệt để này cho thấy Thiên Chúa có thể dùng sinh vật yếu ớt nhất để bẻ gãy mọi thành tựu kiêu ngạo của thủ lãnh Pharaô.' }
  ]}
];
