module.exports = [
  {id:16,theme:'Kinh Thánh Tân Ước',words:[
    {answer:'MATTHEU',clue:'Tác giả cuốn Tin Mừng mang biểu tượng người có cánh, viết cho người Do Thái để chứng minh Chúa là Đấng Mêsia.',explanation:'Thánh Mátthêu vốn là một người thu thuế tội lỗi được Chúa gọi. Phúc Âm của ngài trích dẫn nhiều nhất từ Cựu Ước để khẳng định gốc gác vương giả của Chúa Giêsu.'},
    {answer:'MACCO',clue:'Tác giả cuốn Tin Mừng ngắn gọn nhất mang biểu tượng sư tử, theo sát từng bước chân rao giảng của Chúa Giêsu.',explanation:'Thánh Máccô ghi lại ít bài giảng nhưng tập trung miêu tả các phép lạ hùng hồn để chứng tỏ Chúa Giêsu có quyền năng dẹp tan ma quỷ.'},
    {answer:'LUCA',clue:'Vị bác sĩ tài ba viết Tin Mừng mang biểu tượng con bò, ghi lại nhiều dụ ngôn nhất về lòng thương xót.',explanation:'Thánh Luca đặc biệt ưu ái viết về người nghèo, phụ nữ và những kẻ lạc bước. Những dụ ngôn tuyệt đẹp như Người Cha Nhân Hậu hay người Samaria chỉ có trong sách này.'},
    {answer:'GIOAN',clue:'Vị tông đồ viết Tin Mừng mang biểu tượng đại bàng, đưa người đọc bay cao vào những chiêm niệm sâu thẳm.',explanation:'Khác với lối miêu tả trần thuật tuần tự, Phúc Âm Gioan dạt dào tính thần học sâu sắc, trình bày Chúa Giêsu là Ngôi Lời (Logos) hằng vinh hiển.'},
    {answer:'PHAOLO',clue:'Tác giả vĩ đại đóng góp đến mười bốn bức thư tín trong Tân Ước, dù ngài không thuộc nhóm mười hai tông đồ ban đầu.',explanation:'Từng bách hại Hội Thánh quyết liệt nhưng sau khi được ơn trở lại, ngài trở thành vị tông đồ truyền giáo không mệt mỏi cho các dân ngoại.'},
    {answer:'KHAIHUYEN',clue:'Cuốn sách cuối cùng mang tính mặc khải, dùng vô số hình ảnh thị kiến để báo trước khải hoàn ca của Chiên Con.',explanation:'Sách Khải Huyền do thánh Gioan viết khi bị lưu đày ở Patmos, truyền tải thông điệp hy vọng mạnh mẽ cho các Kitô hữu đang chịu bách hại.'},
  ]},
  {id:17,theme:'Kinh Thánh Cựu Ước',words:[
    {answer:'SANGTHE',clue:'Cuốn sách đầu tiên mở ra lịch sử vũ trụ với trình thuật tuyệt đẹp về nguồn gốc muôn loài do tay Chúa nhào nặn.',explanation:'Sáng Thế Ký không phải là sách khoa học tự nhiên mà là một bài ca tôn giáo, khẳng định muôn loài tồn tại là do ý chí yêu thương của Thiên Chúa.'},
    {answer:'XUATHANH',clue:'Cuốn sách hùng tráng ghi lại cuộc thoát ly vĩ đại khỏi ách nô lệ Ai Cập và phép lạ rẽ nước vượt Biển Đỏ.',explanation:'Sách Xuất Hành kể về biến cố trọng đại nhất của Cựu Ước: Môsê dẫn dắt dân Chúa khỏi ách nô lệ, là hình ảnh tiên báo sự giải phóng của bí tích Rửa Tội sau này.'},
    {answer:'THANHVINH',clue:'Bộ sưu tập gồm một trăm năm mươi bài thánh ca ngợi khen và than van, là xương sống của Phụng vụ Giờ Kinh.',explanation:'Được truyền thống gắn bó phần lớn với Thánh vương Đavít, các bài Thánh Vịnh diễn tả mọi cung bậc cảm xúc vui buồn, thống hối và hy vọng của tâm hồn trước Thiên Chúa.'},
    {answer:'ISAIA',clue:'Vị ngôn sứ vĩ đại nhất cất tiếng tiên báo chi tiết về Người Tôi Tớ Đau Khổ và sự xuất hiện của Đấng Emmanuel.',explanation:'Sách Isaia dài và sâu sắc đến độ được mệnh danh là "Phúc Âm thứ năm". Những lời tiên tri của ngài về Chúa Giêsu rất chi tiết và ấn tượng lạ lùng.'},
    {answer:'CHAMNGON',clue:'Tập sách đúc kết những lời răn dạy khôn ngoan ngắn gọn súc tích, thường được truyền thuyết gắn liền với vua Salômôn.',explanation:'Sách Châm Ngôn dạy cách sống khôn ngoan ở đời, biết kính sợ Đức Chúa là khởi đầu sự khôn ngoan và xa lánh nẻo đường ngông cuồng.'},
    {answer:'DANIEN',clue:'Vị ngôn sứ can đảm bị ném vào hầm sư tử đói hung dữ nhưng vẫn bình an sống sót nhờ lòng trông cậy vào Chúa.',explanation:'Dù làm quan cho vua ngoại bang, Đanien vẫn kiên quyết không thờ lạy tà thần. Niềm tin bất khuất của ông đã được Chúa che chở, khóa chặt miệng sư tử.'},
  ]},
  {id:18,theme:'Mầu Nhiệm Cứu Độ',words:[
    {answer:'NHAPTHE',clue:'Hồng ân kỳ diệu khi Ngôi Lời vô hình hạ thân khoác lấy xác phàm con người trong cung lòng Đức Mẹ Maria.',explanation:'Mầu Nhiệm Nhập Thể cho thấy tình yêu tự hủy: Vị Thiên Chúa tối cao lại chấp nhận giới hạn kiếp người, sinh ra thấp hèn trong máng cỏ tăm tối.'},
    {answer:'CUUCHUOC',clue:'Cái giá vô giá bằng chính Mạng Sống và Bửu Huyết Đức Kitô để giải thoát nhân loại khỏi ách nô lệ tội lỗi ma quỷ.',explanation:'Chúa Giêsu là Chiên Thiên Chúa, đã đổ máu mình ra làm giá chuộc muôn người, gánh lấy mọi hình phạt lỗi lầm thay cho nhân loại.'},
    {answer:'NGUYENTOI',clue:'Tình trạng thiếu hụt ân sủng di truyền từ sự sa ngã của tổ tông Ađam và Evà, làm suy yếu bản tính con người.',explanation:'Tội nguyên tổ là hậu quả của sự kiêu ngạo muốn chối bỏ quyền tể trị của Thiên Chúa ngay từ buổi đầu, khiến nhân loại phải chịu đau khổ và sự chết.'},
    {answer:'ANSUNG',clue:'Món quà siêu nhiên Chúa ban nhưng không, giúp con người có đủ nội lực đánh bại cám dỗ và hướng thiện làm việc lành.',explanation:'Không ai có thể tự mình giành lấy vé vào Thiên Đàng. Ân sủng là sự trợ lực thiêng liêng từ cao xanh, cho phép chúng ta tham dự vào đời sống của Thiên Chúa.'},
    {answer:'THIENDANG',clue:'Quê hương đích thực và viên mãn nhất, nơi linh hồn trong sạch được diện kiến thánh nhan dung quang Chúa muôn đời.',explanation:'Thiên Đàng là vương quốc của hạnh phúc tuyệt hảo, nơi con người được vĩnh viễn hiệp thông trọn vẹn với Thiên Chúa và các thánh, không còn đau khổ khóc than.'},
    {answer:'LUYENNGUC',clue:'Trạng thái thanh luyện đau đớn của các linh hồn đã qua đời trong ơn nghĩa Chúa, nhưng vẫn còn những vướng mắc tội lỗi chưa đền trả hết.',explanation:'Linh hồn ở Luyện Ngục là những người đã nắm chắc phần rỗi, đang thao thức chờ được ngọn lửa tình yêu thanh lọc hoàn toàn để tinh tuyền bước vào Tiệc Cưới.'},
  ]},
  {id:19,theme:'Vật Dụng Phụng Vụ',words:[
    {answer:'BANTHO',clue:'Bàn bằng đá hoặc khối gỗ trang trọng đặt giữa cung thánh, tượng trưng cho chính Chúa Kitô và là nơi dâng hiến tế.',explanation:'Bàn thờ không phải chiếc bàn thông thường. Linh mục cung kính hôn bàn thờ lúc đầu lễ vì nơi đây sẽ hiện tại hóa mầu nhiệm Hy Tế Thập giá Canvê.'},
    {answer:'CHENTHANH',clue:'Chiếc ly cao quý mạ vàng hay bạc được linh mục sử dụng dâng rượu nho trong phần Phụng vụ Thánh Thể.',explanation:'Chiếc chén dùng để đựng Bửu Huyết cực thánh của Chúa. Trong Bữa Tiệc Ly, chính Đức Giêsu đã thiết lập Giao Ước Mới và vĩnh cửu trong chiếc chén này.'},
    {answer:'AOLE',clue:'Phẩm phục lộng lẫy mặc ngoài cùng mà linh mục khoác lên khi dâng lễ, có màu sắc thay đổi luân phiên theo mùa.',explanation:'Áo lễ diễn tả "ách của Chúa" mà linh mục mang vào. Màu Tím chỉ Mùa Vọng/Chay, Trắng Mùa Giáng Sinh/Phục Sinh, Đỏ dùng cho Lễ Tử Đạo hoặc Chúa Thánh Thần.'},
    {answer:'NENPHUCSINH',clue:'Cây nến lớn trang trọng khắc chữ Alpha và Omega, đại diện cho Đức Kitô bừng lên uy nghi phá tan bóng tối tử thần.',explanation:'Nến Phục Sinh tỏa sáng trong Đêm Canh Thức và sáng suốt 50 ngày sau đó. Năm hạt hương ghim trên nến tượng trưng cho vinh quang của Năm Dấu Thánh.'},
    {answer:'NHATAM',clue:'Chiếc tủ nhỏ kiên cố tinh xảo, thường lót nhung đỏ, dùng để cất giữ cẩn thận Mình Thánh Chúa giữa giáo đường.',explanation:'Nhà Tạm luôn đi kèm với một bóng đèn chầu thắp sáng cả ngày đêm, báo hiệu mầu nhiệm Thánh Thể đang hiện diện thực sự nơi trần gian.'},
    {answer:'MATNHAT',clue:'Khung kính viền kim loại mang hình hào quang mặt trời tỏa sáng rực rỡ, ôm trọn bánh Thánh cho các buổi chầu.',explanation:'Mặt Nhật được dùng trong những giờ Chầu Thánh Thể, để mọi ánh mắt tín hữu đều có thể quy hướng chiêm ngắm tấm Bánh Hằng Sống thiêng liêng.'},
  ]},
  {id:20,theme:'Tước Hiệu Chúa Giêsu',words:[
    {answer:'MESIA',clue:'Từ ngữ gốc Do Thái có ý nghĩa là Đấng được xức dầu, Vị Cứu Tinh mà muôn dân hằng thiết tha mong đợi.',explanation:'Người Do Thái xưa mong đợi một Mêsia theo kiểu anh hùng giải phóng chính trị, nhưng Chúa Giêsu đến tỏ mình là Đấng Mêsia Cứu Thế qua con đường thập giá hy sinh.'},
    {answer:'EMMANUEN',clue:'Hồng danh vĩ đại mang ý nghĩa là "Thiên Chúa ở cùng chúng ta", từng được thiên thần báo mộng làm cho thánh Giuse an tâm.',explanation:'Ý nghĩa tước hiệu này diễn tả tình yêu nhập thể: Thiên Chúa đã từ bỏ vinh quang trời cao để cắm lều ở giữa nhân loại và đồng hành trong nỗi đau của chúng ta.'},
    {answer:'NGOILOI',clue:'Danh hiệu mà thánh Gioan dùng để diễn tả Ngôi Hai Thiên Chúa đã hiện hữu từ muôn thuở trước khi đất trời được tạo thành.',explanation:'Ngôi Lời (Logos) là Lời sống động duy nhất của Chúa Cha. Cả công trình sáng tạo vạn vật đều được tác tạo một cách màu nhiệm qua Ngôi Lời.'},
    {answer:'KITOVUA',clue:'Tước vị cao trọng bậc nhất khẳng định Chúa Giêsu là đấng cai quản tối cao của toàn cõi trời đất vũ trụ hữu hình và vô hình.',explanation:'Vương quốc mà Vua Giêsu hiển trị không dùng sức mạnh vũ trang bạo lực, mà là vương quốc của sự thật, bình an và tình yêu xót thương.'},
    {answer:'MUCTU',clue:'Hình ảnh vị thao thức dịu dàng vác con chiên trên vai, luôn sẵn sàng xả thân hy sinh mạng sống bất cứ lúc nào để bảo vệ đàn chiên.',explanation:'Chúa là Mục Tử nhân lành, đi trước dẫn đường cho chiên. Khác với người làm thuê tháo chạy khi sói đến, Ngài đứng ra đương đầu và bảo vệ bầy đoàn vô sự.'},
    {answer:'CHIENCON',clue:'Loài con vật bé nhỏ vô tội dùng để hiến tế. Gọi bằng tước hiệu này, thánh Gioan Tẩy Giả đã giới thiệu Chúa lúc đang cử hành phép rửa ở bờ sông.',explanation:'Chiên Con hàm ý về con chiên chịu sát tế Lễ Vượt Qua. Thay thế nghi lễ cổ xưa bôi máu cửa, nay Máu cực thánh Đức Kitô tuôn đổ rửa sạch tội khiên.'},
  ]},
  { id: 105, theme: 'XH 5: Pharaô Bắt Nạt', words: [
    { answer: 'PHARAO', clue: 'Vị vua kiêu ngạo của Ai Cập đã ngang ngược thách thức: "Đức Chúa là ai mà ta phải nghe lời?"', explanation: 'Sự cứng lòng của Pharaô là đại diện cho quyền lực trần thế, mù quáng khước từ quyền tể trị của Thiên Chúa.' },
    { answer: 'TUCHOI', clue: 'Sự cự tuyệt dai dẳng của vua Ai Cập khi không chịu phóng thích dân Israel đi tế lễ.', explanation: 'Việc cố chấp từ chối này đã châm ngòi cho hàng loạt tai ương kinh hoàng giáng xuống đất nước Ai Cập.' },
    { answer: 'ROM', clue: 'Vật liệu rơm rạ trộn đất mà bọn cai ngục không chịu cung cấp nữa, bắt dân phải tự đi nhặt lấy.', explanation: 'Việc bắt dân tự đi kiếm rơm mà vẫn phải nộp đủ chỉ tiêu gạch là hình phạt tàn nhẫn nhằm dập tắt ý chí nổi dậy của họ.' },
    { answer: 'GACH', clue: 'Khối đất sét nung hình chữ nhật mà dân Israel phải khổ nhọc đóng khuôn mỗi ngày.', explanation: 'Gạch là biểu tượng của sự lao động trĩu nặng mồ hôi nước mắt mà đế chế ngoại bang đè bóp lên vai dân Chúa.' },
    { answer: 'NANGNE', clue: 'Trách nhiệm lao dịch thêm phần khắc nghiệt giáng xuống đầu mọi người sau khi Môsê ra mặt can thiệp.', explanation: 'Gánh nặng dồn dập khiến dân bức xúc oán trách Môsê, đẩy ông vào tình thế tuyệt vọng phải tha thiết kêu xin ơn Chúa.' },
    { answer: 'CAIQUAN', clue: 'Viên chức quản đốc đánh đập những người Híp-ri vì họ không nộp đúng mức chỉ tiêu quy định.', explanation: 'Sự áp bức của các viên cai quản phản ánh hệ thống nô lệ tàn tạ, tước đoạt tàn nhẫn nhân phẩm của con người.' }
  ]},
  { id: 106, theme: 'XH 6: Giao Ước Được Nhắc Lại', words: [
    { answer: 'GIAVE', clue: 'Danh xưng thiêng liêng YHWH mà Thiên Chúa tuyên bố chưa từng tiết lộ cho các tổ phụ xưa kia.', explanation: 'Danh xưng này mang ý nghĩa sự hiện diện giải phóng chủ động. Ngài không chỉ là Đấng Tạo Hóa, mà còn là Đấng Cứu Chuộc.' },
    { answer: 'ABRAHAM', clue: 'Vị tổ phụ đầu tiên của đức tin được Chúa nhắc đến để khẳng định Ngài luôn nhớ mãi giao ước lâu đời.', explanation: 'Thiên Chúa của Abraham, Ixaac, Giacop bảo chứng rằng lịch sử gian truân của dân tộc nằm trọn trong kế hoạch yêu thương của Ngài.' },
    { answer: 'IXAAC', clue: 'Người con trai của lời hứa, được nhắc nhở tiếp nối dòng dõi được Thiên Chúa ban tặng đất hứa bao la.', explanation: 'Việc nhắc tên Ixaac nối kết lời thề với các thế hệ quá khứ để làm điểm tựa vững chắc cho khát vọng tự do của hiện tại.' },
    { answer: 'GIACOP', clue: 'Vị tổ phụ mang tên mới là Israel, cha của mười hai chi tộc đang rên xiết dưới gánh nặng nô lệ.', explanation: 'Danh xưng con cái Israel gợi lên niềm tự hào dân tộc và quyền lợi chính đáng để bảo vệ căn tính của họ trước Ai Cập.' },
    { answer: 'GIAOUOC', clue: 'Lời thề hứa bền chặt mà Thiên Chúa đã lập ra để ban cho dân Đất Hứa làm gia nghiệp vĩnh viễn.', explanation: 'Giao ước là văn bản tình yêu vô điều kiện: "Ta sẽ nhận các ngươi làm dân Ta, và Ta sẽ là Thiên Chúa của các ngươi."' },
    { answer: 'XUAT', clue: 'Hành động dứt khoát đưa dân ra khỏi đất Ai Cập bằng một cánh tay giơ cao quyền phép tột đỉnh.', explanation: 'Cuộc Xuất Hành không chỉ là một cuộc thiên di lịch sử, mà còn là một hành trình thanh tẩy đức tin để trở thành một dân thánh hiến.' }
  ]}
];
